import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, '..')
const releasesDir = path.join(projectRoot, 'releases', 'changelog')
const outputFile = path.join(projectRoot, 'src', 'data', 'changelog.generated.ts')
const locales = ['zh-CN', 'en']

function assert(condition, message) {
  if (!condition) {
    throw new Error(message)
  }
}

function validateLocalizedText(value, label) {
  assert(value && typeof value === 'object' && !Array.isArray(value), `${label} must be an object.`)
  for (const locale of locales) {
    assert(typeof value[locale] === 'string' && value[locale].trim(), `${label}.${locale} must be a non-empty string.`)
  }
}

function parseVersion(version) {
  const parts = version.split('.').map((part) => Number.parseInt(part, 10))
  assert(parts.length === 3 && parts.every(Number.isInteger), `Version "${version}" must use major.minor.patch format.`)
  return parts
}

function compareVersions(a, b) {
  const left = parseVersion(a)
  const right = parseVersion(b)
  for (let i = 0; i < left.length; i += 1) {
    if (left[i] !== right[i]) return right[i] - left[i]
  }
  return 0
}

function loadEntries() {
  const files = readdirSync(releasesDir)
    .filter((file) => file.endsWith('.json'))
    .sort()

  assert(files.length > 0, 'No changelog release files were found.')

  const seenVersions = new Set()
  const entries = files.map((file) => {
    const fullPath = path.join(releasesDir, file)
    const raw = readFileSync(fullPath, 'utf8')
    const entry = JSON.parse(raw)
    const expectedVersion = path.basename(file, '.json')

    assert(typeof entry.version === 'string' && entry.version, `${file}: version must be a non-empty string.`)
    assert(entry.version === expectedVersion, `${file}: filename must match version "${entry.version}".`)
    assert(!seenVersions.has(entry.version), `${file}: duplicate version "${entry.version}".`)
    seenVersions.add(entry.version)

    assert(typeof entry.date === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(entry.date), `${file}: date must use YYYY-MM-DD.`)
    validateLocalizedText(entry.headline, `${file}: headline`)
    validateLocalizedText(entry.summary, `${file}: summary`)
    assert(Array.isArray(entry.sections) && entry.sections.length > 0, `${file}: sections must be a non-empty array.`)

    entry.sections.forEach((section, sectionIndex) => {
      validateLocalizedText(section.heading, `${file}: sections[${sectionIndex}].heading`)
      assert(Array.isArray(section.items) && section.items.length > 0, `${file}: sections[${sectionIndex}].items must be a non-empty array.`)
      section.items.forEach((item, itemIndex) => {
        validateLocalizedText(item.title, `${file}: sections[${sectionIndex}].items[${itemIndex}].title`)
        if (item.description !== undefined) {
          validateLocalizedText(item.description, `${file}: sections[${sectionIndex}].items[${itemIndex}].description`)
        }
      })
    })

    return entry
  })

  return entries.sort((a, b) => {
    const versionCompare = compareVersions(a.version, b.version)
    if (versionCompare !== 0) return versionCompare
    return b.date.localeCompare(a.date)
  })
}

function render(entries) {
  const body = JSON.stringify(entries, null, 2)
  return `// This file is auto-generated by \`npm run changelog:build\`.\n// Do not edit manually. Update JSON files in \`releases/changelog/\` instead.\n\nimport type { ChangelogEntry } from './changelog.schema'\n\nexport const CHANGELOG: ChangelogEntry[] = ${body}\n`
}

function main() {
  const command = process.argv[2] ?? '--check'
  assert(command === '--check' || command === '--write', 'Use --check or --write.')

  const entries = loadEntries()
  const nextOutput = render(entries)

  if (command === '--write') {
    writeFileSync(outputFile, nextOutput, 'utf8')
    console.log(`Updated ${path.relative(projectRoot, outputFile)}`)
    return
  }

  if (!existsSync(outputFile)) {
    throw new Error('Generated changelog file is missing. Run `npm run changelog:build`.')
  }

  const currentOutput = readFileSync(outputFile, 'utf8')
  if (currentOutput !== nextOutput) {
    throw new Error('Generated changelog is stale. Run `npm run changelog:build`.')
  }

  console.log('Changelog files are in sync.')
}

try {
  main()
} catch (error) {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
}
