// This file is auto-generated by `npm run changelog:build`.
// Do not edit manually. Update JSON files in `releases/changelog/` instead.

import type { ChangelogEntry } from './changelog.schema'

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "0.1.17",
    "date": "2026-05-19",
    "headline": {
      "zh-CN": "后台曲目救援操作不再强制填写原因",
      "en": "Admin track rescue actions no longer require a reason"
    },
    "summary": {
      "zh-CN": "管理后台的曲目救援操作现在可以直接执行，无需为强制状态、重分配、重开、归档、恢复或删除额外填写原因。账号治理类操作仍会保留必填原因。",
      "en": "Admin track rescue actions can now run without an extra reason for force status, reassignment, reopen, archive, restore, or delete operations. Account governance actions still keep their required reason field."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "管理后台",
          "en": "Admin console"
        },
        "items": [
          {
            "title": {
              "zh-CN": "曲目工作流操作的原因改为选填",
              "en": "Track workflow action reasons are now optional"
            },
            "description": {
              "zh-CN": "曲目救援区的原因输入框已标记为选填；留空时系统不再自动写入默认文案，审计记录会保留为空原因。",
              "en": "The reason field in the track rescue area is now marked optional. Leaving it blank no longer inserts default copy, and audit entries keep the reason empty."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.16",
    "date": "2026-05-12",
    "headline": {
      "zh-CN": "修正最近更新的审核跳转",
      "en": "Fixes recent-update review navigation"
    },
    "summary": {
      "zh-CN": "Dashboard 顶部的「最近更新」现在会按当前用户权限打开曲目：有待处理动作时进入对应审核工作台，没有动作权限时只打开普通曲目详情页。",
      "en": "The Dashboard recent-updates panel now opens tracks according to the current user's permissions: tracks with pending actions still open the review workspace, while tracks without action permission open the normal track detail page."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "Dashboard",
          "en": "Dashboard"
        },
        "items": [
          {
            "title": {
              "zh-CN": "最近更新不再误入审核界面",
              "en": "Recent updates no longer open review pages incorrectly"
            },
            "description": {
              "zh-CN": "没有审核动作权限的用户点击「最近更新」里的曲目时，会停留在曲目详情上下文，不再跳转到该曲目的审核阶段页面。",
              "en": "When users without review action permission click a track in Recent Updates, they now land in the track detail context instead of being sent to that track's review-stage page."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.15",
    "date": "2026-05-11",
    "headline": {
      "zh-CN": "新增亮色主题与同行评审快速返修模式",
      "en": "Adds a light theme and expedited peer-review revision mode"
    },
    "summary": {
      "zh-CN": "Back Kitchen 现在保留默认暗色外观，同时新增可切换的亮色主题；主催也可以在工作流中开启“任一评审打回即返修”模式，让评审人把建议打回和直接要求重新上传分开处理。",
      "en": "Back Kitchen now keeps the dark theme as the default while adding a switchable light theme. Producers can also enable an “any reviewer can request re-upload” workflow mode so reviewers can separate revision recommendations from direct re-upload requests."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "界面主题",
          "en": "Interface theme"
        },
        "items": [
          {
            "title": {
              "zh-CN": "可在暗色与亮色之间切换",
              "en": "Switch between dark and light"
            },
            "description": {
              "zh-CN": "页头和登录相关页面新增主题按钮；亮色主题使用暖白背景、浅灰分层和橙色主操作，便于在明亮环境中预览和审核。",
              "en": "The header and auth pages now include a theme button. The light theme uses warm off-white backgrounds, soft dividers, and orange primary actions for brighter review environments."
            }
          },
          {
            "title": {
              "zh-CN": "优化亮色主题状态色和封面占位图",
              "en": "Refines light-theme badges and cover placeholders"
            },
            "description": {
              "zh-CN": "亮色主题下通知、更新徽标、侧栏角标、主按钮、勾选框、波形标注和工作流编辑器的阶段高亮改为更柔和的语义色片；已解决的波形标注不再使用突兀的绿色，专辑进度条改为更明亮但低饱和的图表色。没有上传封面的专辑现在使用随主题变化的浅色唱片占位图。",
              "en": "In the light theme, notification and update badges, sidebar badges, primary buttons, checkboxes, waveform markers, and workflow-editor stage highlights now use softer semantic chips. Resolved waveform markers no longer use the prominent green, while album progress bars use brighter low-saturation chart colors. Albums without covers render a theme-aware placeholder instead of the fixed dark record art."
            }
          },
          {
            "title": {
              "zh-CN": "侧栏新增个人中心入口",
              "en": "Adds a sidebar profile shortcut"
            },
            "description": {
              "zh-CN": "侧栏底部的头像与用户名区域现在可以直接进入个人中心；桌面折叠状态和移动端抽屉中也保持相同入口。",
              "en": "The sidebar avatar and name area now opens the profile page directly, including collapsed desktop and mobile drawer layouts."
            }
          },
          {
            "title": {
              "zh-CN": "移除飞书提及前端配置",
              "en": "Removes Feishu mention setup from the frontend"
            },
            "description": {
              "zh-CN": "专辑 Webhook 设置不再显示飞书 App ID、App Secret 与 @ 提及配置；个人资料页也不再显示飞书联系方式字段。",
              "en": "Album webhook settings no longer show Feishu App ID, App Secret, or @mention setup fields, and profile settings no longer show the Feishu contact field."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "建议打回和直接返修分开处理",
              "en": "Revision recommendations and direct re-upload are now separate"
            },
            "description": {
              "zh-CN": "开启新模式后，评审人可以先记录“建议打回”，也可以确认后直接让曲目进入修订阶段。未完成的内部待讨论 issue 不会自动结案，仍可由评审组继续处理或发布给曲师。",
              "en": "When the new mode is enabled, reviewers can record a revision recommendation first or confirm a direct move into revision. Unfinished internal discussion issues are no longer auto-closed and can still be handled by the review group or published to the submitter."
            }
          },
          {
            "title": {
              "zh-CN": "工作流编辑器说明随模式切换",
              "en": "Workflow editor hints now follow the selected mode"
            },
            "description": {
              "zh-CN": "返修触发方式在“达到人数后统一决定”和“任一评审打回即返修”之间切换时，下方说明会同步解释当前模式的实际行为。",
              "en": "When switching the revision trigger between quorum-based decisions and immediate re-upload requests, the helper text now explains the currently selected behavior."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.14",
    "date": "2026-05-11",
    "headline": {
      "zh-CN": "修复重复评审分配显示",
      "en": "Fixes duplicate review assignment display"
    },
    "summary": {
      "zh-CN": "同一评审人在同一评审阶段不会再因为历史分配被重复计数；曲目摘要会按当前有效评审人去重显示，并且后端会阻止新的重复有效分配。",
      "en": "The same reviewer is no longer counted multiple times within one review stage. Track summaries now display current active reviewers once, and the backend prevents new duplicate active assignments."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评审人列表按当前有效分配去重",
              "en": "Reviewer lists now dedupe active assignments"
            },
            "description": {
              "zh-CN": "重新进入同行评审或管理员重新分配评审人时，旧的有效分配会被正确关闭；已有重复记录会在迁移中标记为已取代，不会再把同一评审人显示为多个人。",
              "en": "When a track re-enters peer review or an administrator reassigns reviewers, older active assignments are closed correctly. Existing duplicate records are marked as superseded by the migration so one reviewer no longer appears as multiple reviewers."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.13",
    "date": "2026-05-11",
    "headline": {
      "zh-CN": "修复波形音频偶发加载失败",
      "en": "Fixes intermittent waveform audio loading failures"
    },
    "summary": {
      "zh-CN": "波形播放器现在会直接使用已缓存的音频数据，不再让 Wavesurfer 重新抓取浏览器内部的 blob 地址，减少偶发的 Failed to fetch 播放失败。",
      "en": "The waveform player now loads cached audio data directly instead of asking Wavesurfer to fetch browser-internal blob URLs again, reducing intermittent Failed to fetch playback errors."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "音频播放",
          "en": "Audio playback"
        },
        "items": [
          {
            "title": {
              "zh-CN": "减少波形播放器的 Failed to fetch 错误",
              "en": "Reduced Failed to fetch errors in the waveform player"
            },
            "description": {
              "zh-CN": "当前源音频、版本对比和下载音频都会复用同一份缓存数据；播放器会直接读取 Blob 内容，避免对 blob: 地址进行第二次 fetch。",
              "en": "Current source audio, version comparison, and downloads now reuse the same cached data. The player reads Blob contents directly, avoiding a second fetch of blob: URLs."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.12",
    "date": "2026-05-11",
    "headline": {
      "zh-CN": "修复旧评审记录残留问题",
      "en": "Fixes stale review record cleanup"
    },
    "summary": {
      "zh-CN": "删除曲目后，旧的评审分配、播放偏好和通知引用会被正确清理，避免新曲目复用编号时看到不属于自己的历史评审记录。",
      "en": "Deleted tracks now clean up old review assignments, playback preferences, and notification links correctly, preventing reused track IDs from showing unrelated historical review records."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "旧评审分配不会再挂到新曲目上",
              "en": "Old review assignments no longer attach to new tracks"
            },
            "description": {
              "zh-CN": "后端现在会启用 SQLite 外键检查，并在删除曲目前清理会阻塞删除或造成误关联的引用；迁移也会清除历史数据库中已失效的评审分配和通知链接。",
              "en": "The backend now enables SQLite foreign-key checks and clears references that could block deletion or create false links before a track is removed. The migration also cleans invalid historical review assignments and notification links."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.11",
    "date": "2026-05-10",
    "headline": {
      "zh-CN": "头像刷新后不再显示为坏图",
      "en": "Avatars now keep rendering after refresh"
    },
    "summary": {
      "zh-CN": "修复头像上传成功后刷新页面会从前端站点路径加载图片的问题。头像现在会使用与其他上传资源一致的后端资源地址。",
      "en": "Fixes avatar images loading from the frontend site path after a successful upload. Avatars now use the same backend asset URL handling as other uploaded resources."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "个人资料",
          "en": "Profile"
        },
        "items": [
          {
            "title": {
              "zh-CN": "修复头像上传后的刷新显示",
              "en": "Fixed avatar display after refresh"
            },
            "description": {
              "zh-CN": "个人资料页和侧边栏头像现在会解析到正确的上传资源地址，在前端和后端分开部署时不会再请求错误的 `/uploads` 路径。",
              "en": "Profile and sidebar avatars now resolve to the correct uploaded asset URL, so split frontend/backend deployments no longer request the wrong `/uploads` path."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.10",
    "date": "2026-05-07",
    "headline": {
      "zh-CN": "同行评审页支持快速分配审稿人",
      "en": "Peer review page now supports quick reviewer assignment"
    },
    "summary": {
      "zh-CN": "主催现在可以在同行评审步骤页直接分配或重新分配审稿人，不必返回曲目详情页处理空置的评审阶段。",
      "en": "Producers can now assign or reassign reviewers directly from the peer review step page instead of returning to track details when a review stage is unassigned."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审分配",
          "en": "Review assignment"
        },
        "items": [
          {
            "title": {
              "zh-CN": "主催可在评审协作卡片中分配审稿人",
              "en": "Producers can assign reviewers from the coordination card"
            },
            "description": {
              "zh-CN": "同行评审页的评审协作卡片新增分配入口：手动模式会打开成员选择弹窗，自动或固定评审池则可一键重新触发分配。",
              "en": "The review coordination card now includes an assignment control: manual stages open a member picker, while auto and fixed-pool stages can rerun assignment with one click."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "评论附件",
          "en": "Comment attachments"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评论和问题表单支持直接粘贴图片",
              "en": "Comments and issue forms now accept pasted images"
            },
            "description": {
              "zh-CN": "在问题评论、状态说明、讨论消息和新建问题表单中，可直接从剪贴板粘贴 JPEG、PNG、WebP 或 GIF 图片作为附件。",
              "en": "Issue comments, status notes, discussion messages, and new issue forms now let you paste JPEG, PNG, WebP, or GIF images from the clipboard as attachments."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.9",
    "date": "2026-05-06",
    "headline": {
      "zh-CN": "修复实时连接权限与诊断日志",
      "en": "Fixes real-time connection permissions and diagnostics"
    },
    "summary": {
      "zh-CN": "固定评审池和阶段分配中的评审人现在可以正常建立曲目实时连接；服务器也会记录 WebSocket 握手阶段的异常堆栈，便于排查偶发连接错误。",
      "en": "Reviewers assigned through fixed reviewer pools or stage assignments can now open track real-time connections, and the server records handshake exception traces for easier diagnosis of intermittent connection errors."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "实时协作",
          "en": "Real-time collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评审分配权限同步到 WebSocket",
              "en": "Review assignment permissions now apply to WebSocket access"
            },
            "description": {
              "zh-CN": "曲目实时连接现在与曲目详情页使用一致的可见性规则，固定评审池或阶段分配中的评审人不会再因为旧评审字段为空而被拒绝连接。",
              "en": "Track real-time connections now use the same visibility rules as the track detail page, so fixed-pool and stage-assigned reviewers are no longer rejected when the legacy reviewer field is empty."
            }
          },
          {
            "title": {
              "zh-CN": "握手异常会写入后端日志",
              "en": "Handshake failures now write backend logs"
            },
            "description": {
              "zh-CN": "WebSocket 鉴权和权限检查中的意外异常会记录到后端日志，并按连接错误关闭，避免浏览器只显示 500 而服务器缺少排查线索。",
              "en": "Unexpected errors during WebSocket authentication and access checks are logged on the backend and closed as connection errors, avoiding browser-only 500s without server-side clues."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.8",
    "date": "2026-05-05",
    "headline": {
      "zh-CN": "修复曲目重提与固定评审流程",
      "en": "Fixes track resubmission and fixed-review flows"
    },
    "summary": {
      "zh-CN": "可重新提交的退稿现在能在曲目详情页直接上传新源音频；固定评审允许主催参与同行评审，并修复终审退回母带后的批准状态重置。",
      "en": "Resubmittable rejected tracks can now upload a new source from the detail page. Fixed reviews can include the producer, and final-review returns to mastering now reset approval state correctly."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "工作流",
          "en": "Workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "可重提退稿有了上传入口",
              "en": "Resubmittable rejections now have an upload entry"
            },
            "description": {
              "zh-CN": "当曲目被拒绝但允许重新提交时，曲师可以直接在曲目详情页选择新源音频并回到接收审核阶段。",
              "en": "When a track is rejected with resubmission allowed, the submitter can choose a new source file from the detail page and return the track to intake."
            }
          },
          {
            "title": {
              "zh-CN": "固定评审支持主催参与",
              "en": "Fixed reviews support producer reviewers"
            },
            "description": {
              "zh-CN": "固定评审池现在可以包含主催；系统会按评审分配记录判断权限和计数，提交者本人仍会被排除。",
              "en": "Fixed reviewer pools can include the producer. Permissions and counts follow assignment records, while the track submitter remains excluded."
            }
          },
          {
            "title": {
              "zh-CN": "终审退回母带重置批准状态",
              "en": "Final-review returns reset approval state"
            },
            "description": {
              "zh-CN": "终审退回母带后仍停留在同一工作流轮次内，但会清空当前母带的终审批准状态，后续母带版本继续按交付编号递增。",
              "en": "Returning from final review to mastering stays in the same workflow cycle, clears current master approval state, and keeps later master versions numbered within that cycle."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.7",
    "date": "2026-05-05",
    "headline": {
      "zh-CN": "Webhook 设置新增曲师邮件提醒",
      "en": "Adds composer email reminders to Webhook settings"
    },
    "summary": {
      "zh-CN": "专辑的 Webhook 设置现在可以单独启用曲师邮件提醒。启用后，新的公开问题、公开问题回复，以及退回修订等需要曲师处理的待办，会通过已验证邮箱发送给当前曲目的提交者。",
      "en": "Album Webhook settings can now enable composer email reminders separately. When enabled, new public issues, public issue replies, and revision requests are emailed to the current track submitter's verified email address."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "通知",
          "en": "Notifications"
        },
        "items": [
          {
            "title": {
              "zh-CN": "按专辑启用曲师邮件提醒",
              "en": "Per-album composer email reminders"
            },
            "description": {
              "zh-CN": "制作人可以在专辑的 Webhook 标签页开启「邮件通知曲师」，并选择新公开问题、公开问题回复和请求修订三类触发事件。邮件只发送给对应曲目的提交者，不会写入 Webhook 发送历史。",
              "en": "Producers can enable Email composers from an album's Webhook tab and choose new public issues, public issue replies, and revision requests as triggers. Emails go only to the related track submitter and are kept separate from Webhook delivery history."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.6",
    "date": "2026-05-05",
    "headline": {
      "zh-CN": "新增固定多人评审，并补齐重开与母带确认流程细节",
      "en": "Adds fixed multi-reviewer assignment and tightens reopen and mastering confirmation flows"
    },
    "summary": {
      "zh-CN": "同行评审现在支持自动分配、手动指派和固定多人评审三种模式。固定名单中如果包含投稿者本人，系统会在该曲目中自动排除投稿者；排除后无人可审时会通知主催手动指派。同时修复了直接重开母带备注不保存、母带页重复确认按钮、部分工作流状态文案回退和角色切换时旧请求干扰登录态的问题。",
      "en": "Peer review now supports auto assignment, manual assignment, and fixed multi-reviewer lists. When a fixed list contains the submitter, that person is excluded for their own track; if nobody remains, the producer is notified to assign reviewers manually. This release also fixes direct-reopen mastering notes, duplicate mastering confirmation buttons, missing workflow status labels, and stale requests interfering with newer login state."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "工作流评审",
          "en": "Workflow review"
        },
        "items": [
          {
            "title": {
              "zh-CN": "固定多人评审模式",
              "en": "Fixed multi-reviewer mode"
            },
            "description": {
              "zh-CN": "工作流编辑器新增「固定评审」模式，可为同行评审阶段选择固定评审名单；进入评审时会为所有非投稿者的固定评审人创建待审任务，并要求实际分配到的人全部完成评审。",
              "en": "The workflow editor now has a Fixed reviewers mode for peer review stages. Entering review creates pending assignments for every fixed reviewer who is not the submitter, and all actually assigned reviewers must finish."
            }
          },
          {
            "title": {
              "zh-CN": "自审排除与手动回退",
              "en": "Self-review exclusion and manual fallback"
            },
            "description": {
              "zh-CN": "自动、手动、固定三种模式都继续禁止投稿者审核自己的稿件。固定名单排除投稿者后若无人可审，系统会通知主催手动安排评审。",
              "en": "Auto, manual, and fixed assignment all continue to prevent submitters from reviewing their own tracks. If a fixed list has no reviewer left after excluding the submitter, the producer is notified to assign reviewers manually."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "流程修复",
          "en": "Flow fixes"
        },
        "items": [
          {
            "title": {
              "zh-CN": "直接重开母带阶段会保存备注",
              "en": "Direct mastering reopen now saves notes"
            },
            "description": {
              "zh-CN": "主催直接把已完成曲目重开到母带相关阶段时，弹窗里填写的母带备注现在会同步写回曲目，母带师进入页面即可看到。",
              "en": "When a producer directly reopens a completed track into a mastering-related stage, the mastering notes entered in the dialog are now saved back to the track."
            }
          },
          {
            "title": {
              "zh-CN": "重开同行评审不再重复显示评审人",
              "en": "Reopened peer review no longer duplicates reviewers"
            },
            "description": {
              "zh-CN": "已完成曲目重开到同行评审时，会先清理上一轮的已提交评审任务，再按当前评审模式重新生成待提交列表，避免「评审协作」中出现同一评审人的待提交和已提交重复行。",
              "en": "When a completed track is reopened into peer review, old submitted review tasks are cleared before the current assignment mode rebuilds the pending list, preventing duplicate pending/submitted rows for the same reviewer."
            }
          },
          {
            "title": {
              "zh-CN": "母带确认入口不再重复",
              "en": "Mastering confirmation is no longer duplicated"
            },
            "description": {
              "zh-CN": "母带页保留底部操作栏的确认交付入口，移除了卡片中重复出现的「确认上传无误」按钮。",
              "en": "The mastering page keeps the confirmation action in the bottom action bar and removes the duplicate inline confirm-upload button."
            }
          },
          {
            "title": {
              "zh-CN": "请求和实时连接更稳",
              "en": "Requests and live connections are steadier"
            },
            "description": {
              "zh-CN": "接口重试会重新读取当前 token；旧 token 的 401 不会清掉新登录态。曲目页在路由或登录状态变化时会关闭旧 WebSocket，并忽略旧页面请求的过期结果。",
              "en": "API retries now re-read the current token, and a 401 from an old token no longer clears a newer login. Track pages close stale WebSockets on route or auth changes and ignore outdated page-load results."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.5",
    "date": "2026-04-20",
    "headline": {
      "zh-CN": "补齐多语言覆盖：邮箱验证、重置密码和社团详情页现在会跟随语言切换",
      "en": "Fills in missing translations on email verification, reset password, and circle detail pages"
    },
    "summary": {
      "zh-CN": "过去邮箱验证页整页只有英文、重置密码页的「显示/隐藏密码」无障碍标签总是英文、社团详情页的头像上传按钮和「复制邀请码」无障碍标签也不跟随语言切换；这次把这些遗漏的文案全部接入了多语言系统，切到中文时不会再突兀地冒出英文。",
      "en": "The email verification page used to be English-only, the Show/Hide password aria-label on the reset password page was always English, and the circle detail page's upload-logo button and Copy invite code aria-label ignored the current language. This release routes all of those through the i18n system, so nothing jumps back to English when you're browsing in Chinese."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "多语言修复",
          "en": "Localization fixes"
        },
        "items": [
          {
            "title": {
              "zh-CN": "邮箱验证页整页支持多语言",
              "en": "Email verification page now fully localized"
            },
            "description": {
              "zh-CN": "打开邮箱验证链接后看到的加载、成功、失败三种状态文案，以及「返回登录」按钮和各类错误提示，现在都会按当前语言显示。",
              "en": "The loading, success, and failure copy shown when you open a verification link — plus the Back to sign in button and all error messages — now follow your current language setting."
            }
          },
          {
            "title": {
              "zh-CN": "重置密码页的密码可见性按钮标签",
              "en": "Password visibility toggle on the reset password page"
            },
            "description": {
              "zh-CN": "密码输入框右侧眼睛图标的无障碍标签（屏幕阅读器读出的「显示密码/隐藏密码」）现在会跟随语言切换；链接缺失 token 时的报错也改为多语言文案。",
              "en": "The accessibility label on the eye icon next to the password field (the Show password / Hide password text a screen reader reads) now follows your language, and the missing-token error on that page is translated as well."
            }
          },
          {
            "title": {
              "zh-CN": "社团详情页的头像上传与邀请码复制标签",
              "en": "Circle detail page's upload logo and invite code labels"
            },
            "description": {
              "zh-CN": "社团详情页上传头像按钮、每个邀请码旁「复制」按钮的无障碍标签现在都会按当前语言显示，之前始终是英文。",
              "en": "The upload-logo button and the Copy invite code aria-labels on each invite row now follow your current language; previously both were always English."
            }
          },
          {
            "title": {
              "zh-CN": "专辑设置页的角色标签与保存失败提示",
              "en": "Role label and save-error toast on album settings"
            },
            "description": {
              "zh-CN": "专辑设置页中，管理员身份显示的「Admin」标签、保存工作流失败时的兜底提示，现在都接入了多语言。",
              "en": "On the album settings page, the Admin role badge and the fallback toast shown when saving the workflow fails are now translated."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.4",
    "date": "2026-04-20",
    "headline": {
      "zh-CN": "首页曲目分页、实时连接可重试，以及全站细腻过渡动效",
      "en": "Dashboard pagination, actionable live-connection reconnect, and subtle motion across the app"
    },
    "summary": {
      "zh-CN": "大量曲目的专辑在首页现在分批渲染，列表更流畅；曲目页实时连接断开时会显示重连尝试次数并提供「立即重试」按钮；同时我们在 Toast、弹窗、侧边栏徽标、状态徽章、波形播放器、讨论列表等多处加上了低干扰的过渡动效，整体更顺滑。",
      "en": "Albums with many tracks now render in batches on the dashboard for snappier scrolling. When the track page loses its real-time connection, the banner shows the reconnect attempt count and a Retry now button. On top of that, we've added low-key motion to toasts, modals, sidebar badges, status badges, the waveform player, and discussion lists for an overall smoother feel."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "首页与实时协作",
          "en": "Dashboard & Real-time"
        },
        "items": [
          {
            "title": {
              "zh-CN": "首页曲目列表分批加载",
              "en": "Dashboard track list now loads in batches"
            },
            "description": {
              "zh-CN": "首页曲目表默认显示前 50 首，底部提供「加载更多」按钮并展示当前/总数；切换筛选或搜索会回到初始批次，避免一次渲染上百条造成的卡顿。",
              "en": "The dashboard track table now renders the first 50 tracks and surfaces a Load more button with a visible / total counter. Switching filters or typing in search resets to the initial batch, so big album lists no longer stall the first paint."
            }
          },
          {
            "title": {
              "zh-CN": "实时连接断开时可主动重试",
              "en": "Retry now control on live-connection dropouts"
            },
            "description": {
              "zh-CN": "曲目详情、母带、工作流三处的「实时连接已断开」横幅现在会显示第几次重连尝试，并提供「立即重试」按钮跳过指数退避等待；内部同时修复了一处可能造成双连接的竞态。",
              "en": "The reconnect banner on the track detail, mastering, and workflow pages now shows the current attempt number and offers a Retry now button that skips the exponential-backoff wait. We also patched a race that could briefly open two sockets during manual retry."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "界面质感",
          "en": "Interface polish"
        },
        "items": [
          {
            "title": {
              "zh-CN": "六处界面细节加入轻量过渡",
              "en": "Subtle transitions across six surfaces"
            },
            "description": {
              "zh-CN": "Toast 会从侧边滑入并带邻居挪位动画；通用弹窗背景淡入、面板缩放入场；快捷键面板、侧边栏未读徽标、曲目状态徽章、波形播放器的播放/暂停图标都加入了短促的视觉反馈；聊天和讨论消息列表统一使用一致的上滑入场。",
              "en": "Toasts slide in from the side with neighbors easing into place; the shared modal has a backdrop fade and a scale-in panel; the shortcuts modal, sidebar unread badges, track status badges, and the waveform player's play/pause icon all gained short feedback animations; chat and discussion messages share one slide-up entrance."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.3",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "评论区新增 @issue 问题引用选择器",
      "en": "@issue picker lands in all comment inputs"
    },
    "summary": {
      "zh-CN": "在所有讨论和评论输入框中，输入 @i 即可弹出当前曲目问题的选择器，支持按编号过滤和键盘操作，选中后自动插入 @issue:N 并渲染为可点击的问题链接。",
      "en": "Typing @i in any discussion or comment input now opens a picker of the current track's issues with filter-by-number and full keyboard support. Selecting an item inserts @issue:N, which renders as a clickable issue chip."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审与协作",
          "en": "Review & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评论区新增 @issue 问题引用选择器",
              "en": "Comment inputs gain an @issue reference picker"
            },
            "description": {
              "zh-CN": "在曲目讨论、母带讨论、母带沟通侧边栏、问题详情评论以及创建问题时的描述框中，输入 @i 即可弹出当前曲目问题列表，继续输入数字可按 local_number 前缀过滤。支持 ↑ ↓ 切换、Enter/Tab 插入、Esc 关闭、鼠标点击；选中后自动补齐为 @issue:N。",
              "en": "Track discussions, mastering discussions, the mastering chat sidebar, issue-detail comment boxes, and the issue creation description box now all surface the same @issue picker. Typing @i opens the list of the current track's issues; additional digits filter by local_number prefix. Arrow keys navigate, Enter/Tab inserts, Escape dismisses, and the selected issue is inserted as @issue:N."
            }
          },
          {
            "title": {
              "zh-CN": "修复：曲目讨论中的引用语法提示从未出现",
              "en": "Fix: reference syntax hint never appeared in track discussions"
            },
            "description": {
              "zh-CN": "之前 DiscussionPanel 的 enableReferencePopover 由于 Vue 可选 boolean 属性默认被规范为 false，导致讨论区从未挂载过语法提示 popover。现在该属性默认值显式为 true，讨论框在输入时间戳、标记或问题引用时都会出现语法提示。",
              "en": "DiscussionPanel's enableReferencePopover was effectively forced to false because Vue normalizes unspecified optional boolean props to false, which meant the reference-syntax popover never mounted inside discussion inputs. The default is now explicitly true, so typing timestamps, marker references, or issue references again surfaces the syntax hint."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.2",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "工作流与评审体验更新",
      "en": "Workflow and review improvements"
    },
    "summary": {
      "zh-CN": "本次更新重点补齐了专辑级 checklist 开关、专辑创建时的审稿人分配默认值、修订上传时的问题批量关闭，以及 discussion 音频在 Cloudflare R2 下的上传链路。",
      "en": "This release focuses on album-level checklist policy controls, reviewer assignment defaults during album creation, issue resolution during revision uploads, and the discussion-audio upload path when Cloudflare R2 is enabled."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "工作流与评审",
          "en": "Workflow & Review"
        },
        "items": [
          {
            "title": {
              "zh-CN": "专辑可单独开启或关闭同行评审 checklist",
              "en": "Albums can now enable or disable the peer-review checklist independently"
            },
            "description": {
              "zh-CN": "社团可以设置新专辑的默认 checklist 策略，专辑创建页和设置页也都可以显式覆盖。关闭后，同行评审界面会立即隐藏 checklist 主工作区并解除对应阻塞。",
              "en": "Circles can define the default checklist policy for new albums, while album creation and album settings can explicitly override it. When disabled, the peer-review workspace hides the checklist UI and removes its blocker immediately."
            }
          },
          {
            "title": {
              "zh-CN": "修订版上传支持批量关闭已处理问题",
              "en": "Revision uploads can now resolve selected issues in one step"
            },
            "description": {
              "zh-CN": "作者上传新源版本时，可以同时提交本次修订已解决的问题和说明备注；系统会在同一事务里写入新版本、更新问题状态并留下状态说明。",
              "en": "When uploading a new source revision, submitters can now include the issues resolved in that revision and an optional note. The system updates the source version, issue statuses, and status-note comments in a single transaction."
            }
          },
          {
            "title": {
              "zh-CN": "同行评审 checklist 草稿会保留并提示重新确认",
              "en": "Peer-review checklist drafts now preserve prior answers and prompt reconfirmation"
            },
            "description": {
              "zh-CN": "如果当前 reviewer 在同一轮工作流中已经提交过上一个源版本的 checklist，系统会自动预填答案，并明确提示这是来自旧版本的内容，需要重新保存确认。",
              "en": "If the current reviewer has already submitted a checklist for a previous source version in the same workflow cycle, the answers are prefilled and clearly marked as needing reconfirmation before the review can be completed."
            }
          },
          {
            "title": {
              "zh-CN": "默认审稿人分配切换不再把工作流标签重置成英文",
              "en": "Changing the default reviewer assignment no longer resets workflow labels to English"
            },
            "description": {
              "zh-CN": "在新建专辑页通过快捷控件切换首个同行评审阶段的自动分配或手动指派时，下面的可视化工作流编辑器现在会保留当前界面的语言标签，不会再突然显示英文步骤名。",
              "en": "When producers switch the first peer-review stage between automatic and manual assignment from the quick control on the new album page, the visual workflow editor now keeps step labels in the current UI language instead of unexpectedly reverting them to English."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "上传与附件",
          "en": "Uploads & Attachments"
        },
        "items": [
          {
            "title": {
              "zh-CN": "discussion 音频补齐了 R2 上传路径",
              "en": "Discussion audio now supports the R2 upload path"
            },
            "description": {
              "zh-CN": "当对象存储开启时，曲目讨论和母带讨论中的音频附件会先请求预签名上传，再把对象 key 提交给后端，和现有评论音频链路保持一致。",
              "en": "When object storage is enabled, audio attachments in both track discussions and mastering discussions now use presigned uploads before submitting object keys back to the backend, matching the existing comment-audio flow."
            }
          },
          {
            "title": {
              "zh-CN": "专辑创建页新增评审默认设置",
              "en": "Album creation now includes review-default controls"
            },
            "description": {
              "zh-CN": "创建专辑时可以直接设置首个同行评审阶段是自动分配还是手动分配审稿人，并且可以同时决定该专辑的 checklist 是否默认开启。",
              "en": "Album creation now lets producers choose whether the first peer-review stage uses automatic or manual reviewer assignment, alongside the album’s default checklist policy."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.1",
    "date": "2026-04-17",
    "headline": {
      "zh-CN": "本版本更新概览",
      "en": "Release overview"
    },
    "summary": {
      "zh-CN": "本次更新聚焦专辑封面上传体验，新增 20 MB 专用上限与更清晰的上传提示，且不影响其他图片上传场景。以下为本版本主要变更。",
      "en": "This release focuses on the album cover upload experience, adding a dedicated 20 MB limit and clearer upload feedback without affecting other image upload flows. The key changes in this release are listed below."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "专辑与上传",
          "en": "Albums & Uploads"
        },
        "items": [
          {
            "title": {
              "zh-CN": "专辑封面单独支持最多 20 MB 上传",
              "en": "Album covers now support uploads up to 20 MB"
            },
            "description": {
              "zh-CN": "专辑封面上传改为使用独立的 20 MB 限制，不再复用系统其他图片附件的 10 MB 通用限制；头像、社团 Logo、问题与评论图片等其他上传场景保持原有上限不变。",
              "en": "Album cover uploads now use a dedicated 20 MB limit instead of the shared 10 MB image limit used elsewhere. Other upload flows such as avatars, circle logos, and issue/comment images retain their existing limits."
            }
          },
          {
            "title": {
              "zh-CN": "优化专辑封面上传校验与报错提示",
              "en": "Improved album cover validation and error feedback"
            },
            "description": {
              "zh-CN": "在新建专辑页与专辑设置页中，封面选择阶段会提前校验格式与大小，并对常见上传失败原因给出更明确的提示；若专辑已创建但封面上传失败，也会明确说明后续需要在设置页重新上传。",
              "en": "The new album and album settings pages now validate cover format and size before upload and provide clearer messages for common upload failures. If album creation succeeds but the cover upload fails, the UI now explicitly tells the user to re-upload the cover in album settings."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.0.2",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "通知与评审体验优化",
      "en": "Notification and Review Workflow Polish"
    },
    "summary": {
      "zh-CN": "本次更新重点优化了评论与工作流通知的上下文信息和提示文案，并收紧了评审内部问题的公开权限，减少误通知与误公开。",
      "en": "This release focuses on clearer context and copy in comment and workflow notifications, while tightening publication rules for reviewer-only issues to reduce accidental alerts and unintended exposure."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "通知与协作",
          "en": "Notifications & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评论通知现在会显示更完整的上下文",
              "en": "Comment notifications now include fuller context"
            },
            "description": {
              "zh-CN": "评论相关的飞书 / Webhook 通知现在会显示对应曲目、问题上下文和操作人，群消息里更容易判断是哪首曲子、哪条问题发生了新的互动。",
              "en": "Feishu and webhook notifications for comments now include the related track, issue context, and actor, making it much easier to tell which track and which issue a new interaction belongs to at a glance."
            }
          },
          {
            "title": {
              "zh-CN": "修复评论通知偶发重复发送",
              "en": "Fixed occasional duplicate comment notifications"
            },
            "description": {
              "zh-CN": "修复了同一条评论在外部通知渠道中偶发重复推送的问题，避免群内短时间收到两条内容相同的提醒。",
              "en": "Fixed an issue where the same comment could occasionally be pushed twice through external notification channels, avoiding back-to-back duplicate alerts in group chats."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review Workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "自动流程通知文案更清晰",
              "en": "Automatic workflow notifications are clearer"
            },
            "description": {
              "zh-CN": "需要手动指派评审人、评审重新开启、内部讨论问题自动结案、同行评审人数达标等自动通知已改为更清晰的表述，并会显示触发本次流程推进的操作人。",
              "en": "Automatic notifications for manual reviewer assignment, reopened reviews, automatic closure of internal-discussion issues, and peer-review quorum now use clearer wording and show who triggered the workflow progression."
            }
          },
          {
            "title": {
              "zh-CN": "收紧评审内部问题的公开权限",
              "en": "Publishing reviewer-only issues is now more restricted"
            },
            "description": {
              "zh-CN": "处于“待讨论”或“内部结案”状态的问题，现在只有问题创建者可以重新发布为公开问题，避免其他评审误将仅内部可见的问题暴露给曲师。",
              "en": "Issues in \"pending discussion\" or \"internally resolved\" states can now only be republished as public issues by their original author, preventing other reviewers from accidentally exposing reviewer-only content to submitters."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.0.1",
    "date": "2026-04-17",
    "headline": {
      "zh-CN": "本版本更新概览",
      "en": "Release overview"
    },
    "summary": {
      "zh-CN": "本次更新涵盖评论协作、后台管理、工作流与仪表盘、母带阶段、专辑导出、下载与播放以及安全性等多个方面，包含若干项功能新增、体验优化与问题修复。以下为本版本主要变更。",
      "en": "This release covers comment collaboration, admin management, workflow and dashboard, the mastering stage, album export, downloads and playback, and safety, comprising a number of new features, experience improvements, and bug fixes. The key changes in this release are listed below."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评论与协作",
          "en": "Comments & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "优化讨论区加载表现",
              "en": "Improved discussion panel loading"
            },
            "description": {
              "zh-CN": "曲目详情页的讨论区与母带讨论区默认仅加载最新 20 条，并在列表顶部提供「加载更早的讨论」按钮按需回溯更早内容，避免一次性拉取全部历史影响响应速度。母带沟通侧边栏（聊天室）保持原有的完整加载行为不变。",
              "en": "The discussion panel on the track detail page and the mastering discussion panel now load only the 20 most recent entries by default, with a \"Load earlier discussions\" button at the top of the list for retrieving older content on demand. This avoids fetching the full history upfront, which could affect responsiveness. The mastering communication sidebar (chat) retains its existing full-load behavior."
            }
          },
          {
            "title": {
              "zh-CN": "新增评论中引用问题的能力",
              "en": "Added the ability to reference issues within comments"
            },
            "description": {
              "zh-CN": "在评论中输入 @issue:1 即可引用当前曲目的 1 号问题。问题编号以曲目为单位独立计数，不跨曲目共享，每首曲目均从 1 号起编。",
              "en": "Entering @issue:1 in a comment references issue #1 of the current track. Issue numbering is scoped to each track rather than shared globally, with every track starting from #1."
            }
          },
          {
            "title": {
              "zh-CN": "新增带索引的附件时间戳语法",
              "en": "Added indexed attachment timestamp syntax"
            },
            "description": {
              "zh-CN": "当评论包含多个音频附件时，可使用 a1:01:23、a2:00:45 的格式指向特定附件的特定时间点，便于在评审与沟通中精确定位音频位置。",
              "en": "When a comment contains multiple audio attachments, references in the form a1:01:23 or a2:00:45 may be used to point at a specific moment within a specific attachment, enabling precise audio referencing during review and discussion."
            }
          },
          {
            "title": {
              "zh-CN": "优化问题抽屉交互",
              "en": "Improved issue drawer interaction"
            },
            "description": {
              "zh-CN": "问题抽屉内新增内嵌波形预览与播放控件，无需离开当前页面即可试听并定位时间点。",
              "en": "An inline waveform preview and playback controls have been added to the issue drawer, allowing audition and seeking without leaving the current page."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "后台管理",
          "en": "Admin Console"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新增后台治理与审计能力",
              "en": "Added governance and audit capabilities to the admin console"
            },
            "description": {
              "zh-CN": "管理员可在后台控制台中集中处理账号状态、社团与专辑治理等事务，并可回溯关键操作的审计记录。",
              "en": "Administrators can now centrally manage account status as well as circle and album governance within the admin console, and review an audit trail of key actions."
            }
          },
          {
            "title": {
              "zh-CN": "后台控制台完成全量国际化",
              "en": "Admin console has been fully internationalized"
            },
            "description": {
              "zh-CN": "后台控制台支持中英双语切换，与系统其他界面保持一致。",
              "en": "The admin console now supports switching between Chinese and English, consistent with the rest of the system."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "工作流与仪表盘",
          "en": "Workflow & Dashboard"
        },
        "items": [
          {
            "title": {
              "zh-CN": "优化专辑创建流程",
              "en": "Improved the album creation flow"
            },
            "description": {
              "zh-CN": "新建专辑所需的操作步骤与页面跳转得到进一步精简。",
              "en": "The number of steps and page transitions required to create a new album has been further reduced."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作流模板一致性",
              "en": "Improved consistency across workflow templates"
            },
            "description": {
              "zh-CN": "对多种同行评审 → 主催审批 → 母带 → 终审的工作流变体进行行为对齐，降低在不同模板间切换时的体验差异。",
              "en": "Behavior across multiple peer-review → producer-gate → mastering → final-review workflow variants has been aligned, reducing experience discrepancies when switching between templates."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作流步骤完成后的跳转逻辑",
              "en": "Improved navigation after completing a workflow step"
            },
            "description": {
              "zh-CN": "完成某一步骤后将自动返回曲目详情页，不再停留在已结束的步骤工作台。",
              "en": "Upon completing a step, the view now automatically returns to the track detail page rather than remaining on the finished step workspace."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作台抽屉体验",
              "en": "Improved the workspace drawer experience"
            },
            "description": {
              "zh-CN": "问题的创建、回复与处理可直接在抽屉内完成，无需跳转至独立的问题详情页。",
              "en": "Issue creation, reply, and resolution can now be performed directly within the drawer, without navigating to the standalone issue detail page."
            }
          },
          {
            "title": {
              "zh-CN": "优化仪表盘筛选",
              "en": "Improved dashboard filtering"
            },
            "description": {
              "zh-CN": "被拒曲目不再混入主列表，支持独立加载与筛选。",
              "en": "Rejected tracks are no longer mixed into the main list and can be loaded and filtered independently."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "母带阶段",
          "en": "Mastering Stage"
        },
        "items": [
          {
            "title": {
              "zh-CN": "修复母带侧边栏显示问题，精简母带历史条目",
              "en": "Fixed mastering sidebar visibility and simplified history entries"
            },
            "description": {
              "zh-CN": "修复在特定条件下曲目详情页无法显示母带侧边栏的问题，同时对母带历史条目的视觉呈现进行了精简。",
              "en": "Fixed an issue where the mastering sidebar could fail to display on the track detail page, and streamlined the visual presentation of mastering history entries."
            }
          },
          {
            "title": {
              "zh-CN": "修复母带相关页面的面包屑与入口",
              "en": "Fixed breadcrumbs and entry point on mastering pages"
            },
            "description": {
              "zh-CN": "修复母带相关页面顶部面包屑的标签显示，调整母带沟通入口的视觉权重。",
              "en": "Corrected breadcrumb labels on mastering-related pages and adjusted the visual weight of the mastering communication entry point."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "专辑导出",
          "en": "Album Export"
        },
        "items": [
          {
            "title": {
              "zh-CN": "导出音频自动写入专辑目录号",
              "en": "Exported audio automatically embeds the album catalog number"
            },
            "description": {
              "zh-CN": "专辑目录号（Catalog Number）将自动写入导出音频文件的元数据，便于交付压盘与发行环节使用，同时利于本地归档。",
              "en": "The album catalog number is now automatically written into the metadata of exported audio files, supporting handoff to pressing and distribution as well as local archiving."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "下载与播放",
          "en": "Downloads & Playback"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新增音频缓存机制",
              "en": "Added an audio caching mechanism"
            },
            "description": {
              "zh-CN": "对已播放或已下载的音频进行本地缓存，重复访问时不再重新发起网络请求，响应速度有所提升；缓存容量设有上限，不会无限制占用本地存储。",
              "en": "Previously played or downloaded audio is now cached locally, so repeated access no longer issues new network requests and responsiveness improves. The cache has an upper size limit and will not consume local storage without bound."
            }
          },
          {
            "title": {
              "zh-CN": "评论内音频附件改由受保护的下载路由提供",
              "en": "Audio attachments in comments now served via a protected download route"
            },
            "description": {
              "zh-CN": "评论内的音频附件仅登录且具备相应权限的用户可访问。",
              "en": "Audio attachments within comments are now accessible only to authenticated users with the appropriate permissions."
            }
          },
          {
            "title": {
              "zh-CN": "评论内音频附件的编号顺序稳定化",
              "en": "Stabilized audio attachment ordering within comments"
            },
            "description": {
              "zh-CN": "评论内附件的编号顺序已稳定化，a1:、a2: 等带索引的附件时间戳引用不再因上传顺序或页面刷新而发生偏移。",
              "en": "The numbering order of attachments within comments is now stable, and indexed attachment timestamp references such as a1: or a2: will no longer shift due to upload order or page refreshes."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "安全性",
          "en": "Safety"
        },
        "items": [
          {
            "title": {
              "zh-CN": "关键不可逆操作新增二次确认",
              "en": "Added confirmation prompts for critical irreversible actions"
            },
            "description": {
              "zh-CN": "对关键不可逆操作（包括账号注销、母带交付确认、曲目拒绝等）增加了二次确认流程。",
              "en": "Confirmation dialogs have been added to critical irreversible actions, including account deletion, mastering delivery confirmation, and track rejection."
            }
          },
          {
            "title": {
              "zh-CN": "统一加载、空状态与错误提示",
              "en": "Unified loading, empty, and error states"
            },
            "description": {
              "zh-CN": "对各视图下的加载态、空状态与错误提示进行了统一；注册、上传等场景的输入校验也进一步收紧。",
              "en": "Loading, empty, and error states have been unified across views; input validation for scenarios such as registration and upload has also been tightened."
            }
          }
        ]
      }
    ]
  }
]
