// This file is auto-generated by `npm run changelog:build`.
// Do not edit manually. Update JSON files in `releases/changelog/` instead.

import type { ChangelogEntry } from './changelog.schema'

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "0.1.4",
    "date": "2026-04-20",
    "headline": {
      "zh-CN": "首页曲目分页、实时连接可重试，以及全站细腻过渡动效",
      "en": "Dashboard pagination, actionable live-connection reconnect, and subtle motion across the app"
    },
    "summary": {
      "zh-CN": "大量曲目的专辑在首页现在分批渲染，列表更流畅；曲目页实时连接断开时会显示重连尝试次数并提供「立即重试」按钮；同时我们在 Toast、弹窗、侧边栏徽标、状态徽章、波形播放器、讨论列表等多处加上了低干扰的过渡动效，整体更顺滑。",
      "en": "Albums with many tracks now render in batches on the dashboard for snappier scrolling. When the track page loses its real-time connection, the banner shows the reconnect attempt count and a Retry now button. On top of that, we've added low-key motion to toasts, modals, sidebar badges, status badges, the waveform player, and discussion lists for an overall smoother feel."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "首页与实时协作",
          "en": "Dashboard & Real-time"
        },
        "items": [
          {
            "title": {
              "zh-CN": "首页曲目列表分批加载",
              "en": "Dashboard track list now loads in batches"
            },
            "description": {
              "zh-CN": "首页曲目表默认显示前 50 首，底部提供「加载更多」按钮并展示当前/总数；切换筛选或搜索会回到初始批次，避免一次渲染上百条造成的卡顿。",
              "en": "The dashboard track table now renders the first 50 tracks and surfaces a Load more button with a visible / total counter. Switching filters or typing in search resets to the initial batch, so big album lists no longer stall the first paint."
            }
          },
          {
            "title": {
              "zh-CN": "实时连接断开时可主动重试",
              "en": "Retry now control on live-connection dropouts"
            },
            "description": {
              "zh-CN": "曲目详情、母带、工作流三处的「实时连接已断开」横幅现在会显示第几次重连尝试，并提供「立即重试」按钮跳过指数退避等待；内部同时修复了一处可能造成双连接的竞态。",
              "en": "The reconnect banner on the track detail, mastering, and workflow pages now shows the current attempt number and offers a Retry now button that skips the exponential-backoff wait. We also patched a race that could briefly open two sockets during manual retry."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "界面质感",
          "en": "Interface polish"
        },
        "items": [
          {
            "title": {
              "zh-CN": "六处界面细节加入轻量过渡",
              "en": "Subtle transitions across six surfaces"
            },
            "description": {
              "zh-CN": "Toast 会从侧边滑入并带邻居挪位动画；通用弹窗背景淡入、面板缩放入场；快捷键面板、侧边栏未读徽标、曲目状态徽章、波形播放器的播放/暂停图标都加入了短促的视觉反馈；聊天和讨论消息列表统一使用一致的上滑入场。",
              "en": "Toasts slide in from the side with neighbors easing into place; the shared modal has a backdrop fade and a scale-in panel; the shortcuts modal, sidebar unread badges, track status badges, and the waveform player's play/pause icon all gained short feedback animations; chat and discussion messages share one slide-up entrance."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.3",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "评论区新增 @issue 问题引用选择器",
      "en": "@issue picker lands in all comment inputs"
    },
    "summary": {
      "zh-CN": "在所有讨论和评论输入框中，输入 @i 即可弹出当前曲目问题的选择器，支持按编号过滤和键盘操作，选中后自动插入 @issue:N 并渲染为可点击的问题链接。",
      "en": "Typing @i in any discussion or comment input now opens a picker of the current track's issues with filter-by-number and full keyboard support. Selecting an item inserts @issue:N, which renders as a clickable issue chip."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审与协作",
          "en": "Review & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评论区新增 @issue 问题引用选择器",
              "en": "Comment inputs gain an @issue reference picker"
            },
            "description": {
              "zh-CN": "在曲目讨论、母带讨论、母带沟通侧边栏、问题详情评论以及创建问题时的描述框中，输入 @i 即可弹出当前曲目问题列表，继续输入数字可按 local_number 前缀过滤。支持 ↑ ↓ 切换、Enter/Tab 插入、Esc 关闭、鼠标点击；选中后自动补齐为 @issue:N。",
              "en": "Track discussions, mastering discussions, the mastering chat sidebar, issue-detail comment boxes, and the issue creation description box now all surface the same @issue picker. Typing @i opens the list of the current track's issues; additional digits filter by local_number prefix. Arrow keys navigate, Enter/Tab inserts, Escape dismisses, and the selected issue is inserted as @issue:N."
            }
          },
          {
            "title": {
              "zh-CN": "修复：曲目讨论中的引用语法提示从未出现",
              "en": "Fix: reference syntax hint never appeared in track discussions"
            },
            "description": {
              "zh-CN": "之前 DiscussionPanel 的 enableReferencePopover 由于 Vue 可选 boolean 属性默认被规范为 false，导致讨论区从未挂载过语法提示 popover。现在该属性默认值显式为 true，讨论框在输入时间戳、标记或问题引用时都会出现语法提示。",
              "en": "DiscussionPanel's enableReferencePopover was effectively forced to false because Vue normalizes unspecified optional boolean props to false, which meant the reference-syntax popover never mounted inside discussion inputs. The default is now explicitly true, so typing timestamps, marker references, or issue references again surfaces the syntax hint."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.2",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "工作流与评审体验更新",
      "en": "Workflow and review improvements"
    },
    "summary": {
      "zh-CN": "本次更新重点补齐了专辑级 checklist 开关、专辑创建时的审稿人分配默认值、修订上传时的问题批量关闭，以及 discussion 音频在 Cloudflare R2 下的上传链路。",
      "en": "This release focuses on album-level checklist policy controls, reviewer assignment defaults during album creation, issue resolution during revision uploads, and the discussion-audio upload path when Cloudflare R2 is enabled."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "工作流与评审",
          "en": "Workflow & Review"
        },
        "items": [
          {
            "title": {
              "zh-CN": "专辑可单独开启或关闭同行评审 checklist",
              "en": "Albums can now enable or disable the peer-review checklist independently"
            },
            "description": {
              "zh-CN": "社团可以设置新专辑的默认 checklist 策略，专辑创建页和设置页也都可以显式覆盖。关闭后，同行评审界面会立即隐藏 checklist 主工作区并解除对应阻塞。",
              "en": "Circles can define the default checklist policy for new albums, while album creation and album settings can explicitly override it. When disabled, the peer-review workspace hides the checklist UI and removes its blocker immediately."
            }
          },
          {
            "title": {
              "zh-CN": "修订版上传支持批量关闭已处理问题",
              "en": "Revision uploads can now resolve selected issues in one step"
            },
            "description": {
              "zh-CN": "作者上传新源版本时，可以同时提交本次修订已解决的问题和说明备注；系统会在同一事务里写入新版本、更新问题状态并留下状态说明。",
              "en": "When uploading a new source revision, submitters can now include the issues resolved in that revision and an optional note. The system updates the source version, issue statuses, and status-note comments in a single transaction."
            }
          },
          {
            "title": {
              "zh-CN": "同行评审 checklist 草稿会保留并提示重新确认",
              "en": "Peer-review checklist drafts now preserve prior answers and prompt reconfirmation"
            },
            "description": {
              "zh-CN": "如果当前 reviewer 在同一轮工作流中已经提交过上一个源版本的 checklist，系统会自动预填答案，并明确提示这是来自旧版本的内容，需要重新保存确认。",
              "en": "If the current reviewer has already submitted a checklist for a previous source version in the same workflow cycle, the answers are prefilled and clearly marked as needing reconfirmation before the review can be completed."
            }
          },
          {
            "title": {
              "zh-CN": "默认审稿人分配切换不再把工作流标签重置成英文",
              "en": "Changing the default reviewer assignment no longer resets workflow labels to English"
            },
            "description": {
              "zh-CN": "在新建专辑页通过快捷控件切换首个同行评审阶段的自动分配或手动指派时，下面的可视化工作流编辑器现在会保留当前界面的语言标签，不会再突然显示英文步骤名。",
              "en": "When producers switch the first peer-review stage between automatic and manual assignment from the quick control on the new album page, the visual workflow editor now keeps step labels in the current UI language instead of unexpectedly reverting them to English."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "上传与附件",
          "en": "Uploads & Attachments"
        },
        "items": [
          {
            "title": {
              "zh-CN": "discussion 音频补齐了 R2 上传路径",
              "en": "Discussion audio now supports the R2 upload path"
            },
            "description": {
              "zh-CN": "当对象存储开启时，曲目讨论和母带讨论中的音频附件会先请求预签名上传，再把对象 key 提交给后端，和现有评论音频链路保持一致。",
              "en": "When object storage is enabled, audio attachments in both track discussions and mastering discussions now use presigned uploads before submitting object keys back to the backend, matching the existing comment-audio flow."
            }
          },
          {
            "title": {
              "zh-CN": "专辑创建页新增评审默认设置",
              "en": "Album creation now includes review-default controls"
            },
            "description": {
              "zh-CN": "创建专辑时可以直接设置首个同行评审阶段是自动分配还是手动分配审稿人，并且可以同时决定该专辑的 checklist 是否默认开启。",
              "en": "Album creation now lets producers choose whether the first peer-review stage uses automatic or manual reviewer assignment, alongside the album’s default checklist policy."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.1",
    "date": "2026-04-17",
    "headline": {
      "zh-CN": "本版本更新概览",
      "en": "Release overview"
    },
    "summary": {
      "zh-CN": "本次更新聚焦专辑封面上传体验，新增 20 MB 专用上限与更清晰的上传提示，且不影响其他图片上传场景。以下为本版本主要变更。",
      "en": "This release focuses on the album cover upload experience, adding a dedicated 20 MB limit and clearer upload feedback without affecting other image upload flows. The key changes in this release are listed below."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "专辑与上传",
          "en": "Albums & Uploads"
        },
        "items": [
          {
            "title": {
              "zh-CN": "专辑封面单独支持最多 20 MB 上传",
              "en": "Album covers now support uploads up to 20 MB"
            },
            "description": {
              "zh-CN": "专辑封面上传改为使用独立的 20 MB 限制，不再复用系统其他图片附件的 10 MB 通用限制；头像、社团 Logo、问题与评论图片等其他上传场景保持原有上限不变。",
              "en": "Album cover uploads now use a dedicated 20 MB limit instead of the shared 10 MB image limit used elsewhere. Other upload flows such as avatars, circle logos, and issue/comment images retain their existing limits."
            }
          },
          {
            "title": {
              "zh-CN": "优化专辑封面上传校验与报错提示",
              "en": "Improved album cover validation and error feedback"
            },
            "description": {
              "zh-CN": "在新建专辑页与专辑设置页中，封面选择阶段会提前校验格式与大小，并对常见上传失败原因给出更明确的提示；若专辑已创建但封面上传失败，也会明确说明后续需要在设置页重新上传。",
              "en": "The new album and album settings pages now validate cover format and size before upload and provide clearer messages for common upload failures. If album creation succeeds but the cover upload fails, the UI now explicitly tells the user to re-upload the cover in album settings."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.0.2",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "通知与评审体验优化",
      "en": "Notification and Review Workflow Polish"
    },
    "summary": {
      "zh-CN": "本次更新重点优化了评论与工作流通知的上下文信息和提示文案，并收紧了评审内部问题的公开权限，减少误通知与误公开。",
      "en": "This release focuses on clearer context and copy in comment and workflow notifications, while tightening publication rules for reviewer-only issues to reduce accidental alerts and unintended exposure."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "通知与协作",
          "en": "Notifications & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评论通知现在会显示更完整的上下文",
              "en": "Comment notifications now include fuller context"
            },
            "description": {
              "zh-CN": "评论相关的飞书 / Webhook 通知现在会显示对应曲目、问题上下文和操作人，群消息里更容易判断是哪首曲子、哪条问题发生了新的互动。",
              "en": "Feishu and webhook notifications for comments now include the related track, issue context, and actor, making it much easier to tell which track and which issue a new interaction belongs to at a glance."
            }
          },
          {
            "title": {
              "zh-CN": "修复评论通知偶发重复发送",
              "en": "Fixed occasional duplicate comment notifications"
            },
            "description": {
              "zh-CN": "修复了同一条评论在外部通知渠道中偶发重复推送的问题，避免群内短时间收到两条内容相同的提醒。",
              "en": "Fixed an issue where the same comment could occasionally be pushed twice through external notification channels, avoiding back-to-back duplicate alerts in group chats."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review Workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "自动流程通知文案更清晰",
              "en": "Automatic workflow notifications are clearer"
            },
            "description": {
              "zh-CN": "需要手动指派评审人、评审重新开启、内部讨论问题自动结案、同行评审人数达标等自动通知已改为更清晰的表述，并会显示触发本次流程推进的操作人。",
              "en": "Automatic notifications for manual reviewer assignment, reopened reviews, automatic closure of internal-discussion issues, and peer-review quorum now use clearer wording and show who triggered the workflow progression."
            }
          },
          {
            "title": {
              "zh-CN": "收紧评审内部问题的公开权限",
              "en": "Publishing reviewer-only issues is now more restricted"
            },
            "description": {
              "zh-CN": "处于“待讨论”或“内部结案”状态的问题，现在只有问题创建者可以重新发布为公开问题，避免其他评审误将仅内部可见的问题暴露给曲师。",
              "en": "Issues in \"pending discussion\" or \"internally resolved\" states can now only be republished as public issues by their original author, preventing other reviewers from accidentally exposing reviewer-only content to submitters."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.0.1",
    "date": "2026-04-17",
    "headline": {
      "zh-CN": "本版本更新概览",
      "en": "Release overview"
    },
    "summary": {
      "zh-CN": "本次更新涵盖评论协作、后台管理、工作流与仪表盘、母带阶段、专辑导出、下载与播放以及安全性等多个方面，包含若干项功能新增、体验优化与问题修复。以下为本版本主要变更。",
      "en": "This release covers comment collaboration, admin management, workflow and dashboard, the mastering stage, album export, downloads and playback, and safety, comprising a number of new features, experience improvements, and bug fixes. The key changes in this release are listed below."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评论与协作",
          "en": "Comments & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "优化讨论区加载表现",
              "en": "Improved discussion panel loading"
            },
            "description": {
              "zh-CN": "曲目详情页的讨论区与母带讨论区默认仅加载最新 20 条，并在列表顶部提供「加载更早的讨论」按钮按需回溯更早内容，避免一次性拉取全部历史影响响应速度。母带沟通侧边栏（聊天室）保持原有的完整加载行为不变。",
              "en": "The discussion panel on the track detail page and the mastering discussion panel now load only the 20 most recent entries by default, with a \"Load earlier discussions\" button at the top of the list for retrieving older content on demand. This avoids fetching the full history upfront, which could affect responsiveness. The mastering communication sidebar (chat) retains its existing full-load behavior."
            }
          },
          {
            "title": {
              "zh-CN": "新增评论中引用问题的能力",
              "en": "Added the ability to reference issues within comments"
            },
            "description": {
              "zh-CN": "在评论中输入 @issue:1 即可引用当前曲目的 1 号问题。问题编号以曲目为单位独立计数，不跨曲目共享，每首曲目均从 1 号起编。",
              "en": "Entering @issue:1 in a comment references issue #1 of the current track. Issue numbering is scoped to each track rather than shared globally, with every track starting from #1."
            }
          },
          {
            "title": {
              "zh-CN": "新增带索引的附件时间戳语法",
              "en": "Added indexed attachment timestamp syntax"
            },
            "description": {
              "zh-CN": "当评论包含多个音频附件时，可使用 a1:01:23、a2:00:45 的格式指向特定附件的特定时间点，便于在评审与沟通中精确定位音频位置。",
              "en": "When a comment contains multiple audio attachments, references in the form a1:01:23 or a2:00:45 may be used to point at a specific moment within a specific attachment, enabling precise audio referencing during review and discussion."
            }
          },
          {
            "title": {
              "zh-CN": "优化问题抽屉交互",
              "en": "Improved issue drawer interaction"
            },
            "description": {
              "zh-CN": "问题抽屉内新增内嵌波形预览与播放控件，无需离开当前页面即可试听并定位时间点。",
              "en": "An inline waveform preview and playback controls have been added to the issue drawer, allowing audition and seeking without leaving the current page."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "后台管理",
          "en": "Admin Console"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新增后台治理与审计能力",
              "en": "Added governance and audit capabilities to the admin console"
            },
            "description": {
              "zh-CN": "管理员可在后台控制台中集中处理账号状态、社团与专辑治理等事务，并可回溯关键操作的审计记录。",
              "en": "Administrators can now centrally manage account status as well as circle and album governance within the admin console, and review an audit trail of key actions."
            }
          },
          {
            "title": {
              "zh-CN": "后台控制台完成全量国际化",
              "en": "Admin console has been fully internationalized"
            },
            "description": {
              "zh-CN": "后台控制台支持中英双语切换，与系统其他界面保持一致。",
              "en": "The admin console now supports switching between Chinese and English, consistent with the rest of the system."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "工作流与仪表盘",
          "en": "Workflow & Dashboard"
        },
        "items": [
          {
            "title": {
              "zh-CN": "优化专辑创建流程",
              "en": "Improved the album creation flow"
            },
            "description": {
              "zh-CN": "新建专辑所需的操作步骤与页面跳转得到进一步精简。",
              "en": "The number of steps and page transitions required to create a new album has been further reduced."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作流模板一致性",
              "en": "Improved consistency across workflow templates"
            },
            "description": {
              "zh-CN": "对多种同行评审 → 主催审批 → 母带 → 终审的工作流变体进行行为对齐，降低在不同模板间切换时的体验差异。",
              "en": "Behavior across multiple peer-review → producer-gate → mastering → final-review workflow variants has been aligned, reducing experience discrepancies when switching between templates."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作流步骤完成后的跳转逻辑",
              "en": "Improved navigation after completing a workflow step"
            },
            "description": {
              "zh-CN": "完成某一步骤后将自动返回曲目详情页，不再停留在已结束的步骤工作台。",
              "en": "Upon completing a step, the view now automatically returns to the track detail page rather than remaining on the finished step workspace."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作台抽屉体验",
              "en": "Improved the workspace drawer experience"
            },
            "description": {
              "zh-CN": "问题的创建、回复与处理可直接在抽屉内完成，无需跳转至独立的问题详情页。",
              "en": "Issue creation, reply, and resolution can now be performed directly within the drawer, without navigating to the standalone issue detail page."
            }
          },
          {
            "title": {
              "zh-CN": "优化仪表盘筛选",
              "en": "Improved dashboard filtering"
            },
            "description": {
              "zh-CN": "被拒曲目不再混入主列表，支持独立加载与筛选。",
              "en": "Rejected tracks are no longer mixed into the main list and can be loaded and filtered independently."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "母带阶段",
          "en": "Mastering Stage"
        },
        "items": [
          {
            "title": {
              "zh-CN": "修复母带侧边栏显示问题，精简母带历史条目",
              "en": "Fixed mastering sidebar visibility and simplified history entries"
            },
            "description": {
              "zh-CN": "修复在特定条件下曲目详情页无法显示母带侧边栏的问题，同时对母带历史条目的视觉呈现进行了精简。",
              "en": "Fixed an issue where the mastering sidebar could fail to display on the track detail page, and streamlined the visual presentation of mastering history entries."
            }
          },
          {
            "title": {
              "zh-CN": "修复母带相关页面的面包屑与入口",
              "en": "Fixed breadcrumbs and entry point on mastering pages"
            },
            "description": {
              "zh-CN": "修复母带相关页面顶部面包屑的标签显示，调整母带沟通入口的视觉权重。",
              "en": "Corrected breadcrumb labels on mastering-related pages and adjusted the visual weight of the mastering communication entry point."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "专辑导出",
          "en": "Album Export"
        },
        "items": [
          {
            "title": {
              "zh-CN": "导出音频自动写入专辑目录号",
              "en": "Exported audio automatically embeds the album catalog number"
            },
            "description": {
              "zh-CN": "专辑目录号（Catalog Number）将自动写入导出音频文件的元数据，便于交付压盘与发行环节使用，同时利于本地归档。",
              "en": "The album catalog number is now automatically written into the metadata of exported audio files, supporting handoff to pressing and distribution as well as local archiving."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "下载与播放",
          "en": "Downloads & Playback"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新增音频缓存机制",
              "en": "Added an audio caching mechanism"
            },
            "description": {
              "zh-CN": "对已播放或已下载的音频进行本地缓存，重复访问时不再重新发起网络请求，响应速度有所提升；缓存容量设有上限，不会无限制占用本地存储。",
              "en": "Previously played or downloaded audio is now cached locally, so repeated access no longer issues new network requests and responsiveness improves. The cache has an upper size limit and will not consume local storage without bound."
            }
          },
          {
            "title": {
              "zh-CN": "评论内音频附件改由受保护的下载路由提供",
              "en": "Audio attachments in comments now served via a protected download route"
            },
            "description": {
              "zh-CN": "评论内的音频附件仅登录且具备相应权限的用户可访问。",
              "en": "Audio attachments within comments are now accessible only to authenticated users with the appropriate permissions."
            }
          },
          {
            "title": {
              "zh-CN": "评论内音频附件的编号顺序稳定化",
              "en": "Stabilized audio attachment ordering within comments"
            },
            "description": {
              "zh-CN": "评论内附件的编号顺序已稳定化，a1:、a2: 等带索引的附件时间戳引用不再因上传顺序或页面刷新而发生偏移。",
              "en": "The numbering order of attachments within comments is now stable, and indexed attachment timestamp references such as a1: or a2: will no longer shift due to upload order or page refreshes."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "安全性",
          "en": "Safety"
        },
        "items": [
          {
            "title": {
              "zh-CN": "关键不可逆操作新增二次确认",
              "en": "Added confirmation prompts for critical irreversible actions"
            },
            "description": {
              "zh-CN": "对关键不可逆操作（包括账号注销、母带交付确认、曲目拒绝等）增加了二次确认流程。",
              "en": "Confirmation dialogs have been added to critical irreversible actions, including account deletion, mastering delivery confirmation, and track rejection."
            }
          },
          {
            "title": {
              "zh-CN": "统一加载、空状态与错误提示",
              "en": "Unified loading, empty, and error states"
            },
            "description": {
              "zh-CN": "对各视图下的加载态、空状态与错误提示进行了统一；注册、上传等场景的输入校验也进一步收紧。",
              "en": "Loading, empty, and error states have been unified across views; input validation for scenarios such as registration and upload has also been tightened."
            }
          }
        ]
      }
    ]
  }
]
