// This file is auto-generated by `npm run changelog:build`.
// Do not edit manually. Update JSON files in `releases/changelog/` instead.

import type { ChangelogEntry } from './changelog.schema'

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "0.1.41",
    "date": "2026-07-08",
    "headline": {
      "zh-CN": "主催可在专辑内管理曲目进度",
      "en": "Producers can manage track progress inside albums"
    },
    "summary": {
      "zh-CN": "社团所有者和副主催现在可以在专辑设置里为本社团绑定专辑手动调整曲目阶段；拒绝曲目仍需通过正常工作流或管理员工具处理。",
      "en": "Circle owners and co-producers can now manually adjust track stages from Album Settings for albums bound to their circle, while rejection still stays in workflow actions or admin tools."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "专辑内进度管理",
          "en": "Album-scoped progress management"
        },
        "items": [
          {
            "title": {
              "zh-CN": "进度管理入口移入专辑设置",
              "en": "Progress management lives in Album Settings"
            },
            "description": {
              "zh-CN": "主催和副主催可在自己管理的社团专辑中选择曲目、目标阶段并记录原因，页面会即时刷新曲目状态。",
              "en": "Producers and co-producers can choose a track, target stage, and optional reason inside managed circle albums, with the track status refreshed immediately."
            }
          },
          {
            "title": {
              "zh-CN": "权限边界保持社团范围",
              "en": "Permission boundaries stay circle-scoped"
            },
            "description": {
              "zh-CN": "该入口只适用于绑定到对应社团的专辑，不会开放未绑定专辑、其他社团专辑或普通成员的手动进度变更；拒绝仍通过工作流打回/拒绝或管理员控制台完成。",
              "en": "The entry only works for albums bound to the manager's circle, not unbound albums, other-circle albums, or regular members; rejection remains handled by workflow return/reject actions or the admin console."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.40",
    "date": "2026-07-07",
    "headline": {
      "zh-CN": "副主催可完整协作专辑流程",
      "en": "Co-producers can fully assist album workflows"
    },
    "summary": {
      "zh-CN": "副主催现在会在专辑、曲目、工作流和提交页面获得与后端权限一致的协作入口，同时社团危险区会正确保留所有权边界。",
      "en": "Co-producers now get album, track, workflow, and submission controls that match backend permissions, while circle danger-zone ownership boundaries remain enforced."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "副主催协作",
          "en": "Co-producer collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "专辑与曲目入口不再漏掉副主催",
              "en": "Album and track entry points no longer omit co-producers"
            },
            "description": {
              "zh-CN": "副主催可以看到可管理的社团专辑，进入专辑设置，处理曲目侧主催流程、评审分配、外部曲师代传和成品导出。",
              "en": "Co-producers can see managed circle albums, enter album settings, handle producer-side track workflow controls, manage reviewer assignments, proxy-submit for external composers, and export completed albums."
            }
          },
          {
            "title": {
              "zh-CN": "社团危险区区分协作与所有权",
              "en": "Circle danger zone separates collaboration from ownership"
            },
            "description": {
              "zh-CN": "副主催在社团危险区只会看到离开社团操作；删除社团仍仅限所有者或管理员。",
              "en": "Co-producers now see only the leave-circle action in the danger zone; deleting a circle remains limited to owners or administrators."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.39",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "新建专辑必须选择社团",
      "en": "Requires a circle when creating albums"
    },
    "summary": {
      "zh-CN": "新专辑创建流程现在要求先选择一个可访问社团；已有未关联社团的旧专辑仍可继续查看和管理。",
      "en": "New album creation now requires selecting an accessible circle, while existing legacy albums without a circle remain viewable and manageable."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "专辑创建",
          "en": "Album creation"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新专辑不再支持空社团创建",
              "en": "New albums can no longer be created without a circle"
            },
            "description": {
              "zh-CN": "创建页会要求选择社团；没有可用社团时，会引导用户先创建社团或使用邀请码加入社团。",
              "en": "The creation page now requires a circle selection, and users with no available circles are guided to create a circle or join one with an invite code."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.38",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "放宽专辑设置工作流编辑区",
      "en": "Widens the album settings workflow editor"
    },
    "summary": {
      "zh-CN": "专辑设置页的工作流页签现在使用更宽的编辑工作区，让流程画布和右侧规则面板在大屏上并排显示。",
      "en": "The workflow tab on album settings now uses a wider editor workspace so the canvas and rule inspector can sit side by side on large screens."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "专辑设置",
          "en": "Album settings"
        },
        "items": [
          {
            "title": {
              "zh-CN": "工作流编辑器不再挤在窄列中",
              "en": "Workflow editing no longer sits in a narrow column"
            },
            "description": {
              "zh-CN": "只有工作流页签会切换到宽版容器，基础信息、团队、活动、清单、排序等页签仍保持原有详情页宽度。",
              "en": "Only the workflow tab switches to the wider container, while info, team, activity, checklist, ordering, and other settings tabs keep the existing detail-page width."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.37",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "新增社团副主催协管权限",
      "en": "Adds circle co-producer management permissions"
    },
    "summary": {
      "zh-CN": "社团主催现在可以将成员设为副主催。副主催可协助维护社团资料、邀请码、工作流模板、专辑设置和曲目流程，但不能任命副主催或执行删除社团等所有权操作。",
      "en": "Circle owners can now promote members to co-producers. Co-producers can help manage circle details, invite codes, workflow templates, album settings, and track workflow actions without gaining ownership-only controls."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "社团协作",
          "en": "Circle collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "成员列表支持副主催角色",
              "en": "Member lists now support co-producers"
            },
            "description": {
              "zh-CN": "主催可在社团成员页调整普通成员、母带师和副主催角色；副主催会在成员列表、权限入口和工作流协作中显示为独立身份。",
              "en": "Owners can update member roles between member, mastering engineer, and co-producer from the circle members page, and co-producers appear as a distinct circle role across collaboration views."
            }
          },
          {
            "title": {
              "zh-CN": "副主催可协助处理专辑流程",
              "en": "Co-producers can help run album workflows"
            },
            "description": {
              "zh-CN": "绑定社团的专辑会把副主催纳入 producer 侧流程权限和关键通知，让协管者可以处理审核、模板、团队、归档曲目和曲目排序等工作。",
              "en": "Albums linked to a circle now include co-producers in producer-side workflow permissions and key notifications, covering reviews, templates, teams, archived tracks, and track ordering."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.36",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "修复社团专辑成员范围与邀请码期限",
      "en": "Fixes circle album member scope and invite code duration"
    },
    "summary": {
      "zh-CN": "社团专辑的团队成员选择现在只显示社团成员，曲目作曲者与专辑邀请也会按社团范围校验；社团邀请码最长有效期调整为 365 天。",
      "en": "Circle album team selection now only shows circle members, track composers and album invitations are validated against the circle scope, and circle invite codes can last up to 365 days."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "社团协作",
          "en": "Circle collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "社团专辑用户范围更一致",
              "en": "Circle album user scope is more consistent"
            },
            "description": {
              "zh-CN": "绑定社团的专辑在选择团队成员和提交平台作曲者时会限制在社团用户范围内，通过用户 ID 邀请也会拒绝社团外用户。",
              "en": "Albums linked to a circle now limit team member choices and platform composer submissions to circle users, and User ID invitations reject users outside the circle."
            }
          },
          {
            "title": {
              "zh-CN": "邀请码最长可设为一年",
              "en": "Invite codes can last for one year"
            },
            "description": {
              "zh-CN": "社团邀请码有效期输入上限从 30 天调整为 365 天，前后端校验保持一致。",
              "en": "The circle invite code duration limit is raised from 30 days to 365 days, with matching frontend and backend validation."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.34",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "放宽社团工作流模板页",
      "en": "Widens circle workflow templates"
    },
    "summary": {
      "zh-CN": "社团详情页的工作流模板标签现在会使用更宽的工作区，模板列表和编辑器在大屏上不再挤在中间窄列。",
      "en": "The workflow templates tab on circle details now uses a wider workspace so template cards and the editor no longer sit in a narrow centered column on large screens."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "社团模板",
          "en": "Circle templates"
        },
        "items": [
          {
            "title": {
              "zh-CN": "模板页适配大屏",
              "en": "Templates fit large screens"
            },
            "description": {
              "zh-CN": "模板标签页会单独放宽页面容器，其他社团信息、成员、邀请码和危险操作页仍保持原有详情页宽度。",
              "en": "The templates tab now widens its page container while the info, members, invite codes, and danger tabs keep the existing detail-page width."
            }
          },
          {
            "title": {
              "zh-CN": "列表和编辑器更易浏览",
              "en": "Lists and editing are easier to scan"
            },
            "description": {
              "zh-CN": "模板列表在中大屏使用两列卡片布局，编辑模板时表单信息与工作流编辑器分区显示，编辑器可使用自身的大屏双栏布局。",
              "en": "Template lists use two card columns on medium and large screens, and template editing separates metadata from the workflow editor so the editor can use its own wide two-column layout."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.33",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "修正社团专辑审稿候选池",
      "en": "Fixes circle album reviewer candidates"
    },
    "summary": {
      "zh-CN": "社团专辑的手动指派、自动分配和工作流模板现在统一使用社团成员作为审稿候选，专辑协作成员不再限制审稿池。",
      "en": "Circle albums now use circle members consistently for manual assignment, automatic assignment, and workflow templates, so album collaborators no longer limit the reviewer pool."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "审稿分配",
          "en": "Review assignment"
        },
        "items": [
          {
            "title": {
              "zh-CN": "社团成员可直接进入审稿候选",
              "en": "Circle members can be reviewer candidates"
            },
            "description": {
              "zh-CN": "社团专辑的手动指派弹窗和工作流编辑器会从社团成员读取候选人，并继续排除当前曲目的作曲者。",
              "en": "Manual assignment dialogs and the workflow editor now read candidates from circle members for circle albums while still excluding the current track composers."
            }
          },
          {
            "title": {
              "zh-CN": "保存和自动分配会拒绝社团外用户",
              "en": "Saving and auto assignment reject outside users"
            },
            "description": {
              "zh-CN": "工作流保存、模板保存、手动指派和旧自动候选池都会过滤或拒绝社团外用户，避免错误分配继续出现。",
              "en": "Workflow saves, template saves, manual assignment, and stale automatic pools now filter or reject users outside the circle to prevent invalid reviewer assignment."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.32",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "优化提交页曲师代办说明",
      "en": "Clarifies upload-page composer proxy guidance"
    },
    "summary": {
      "zh-CN": "曲目提交页补充艺术家 UID 绑定和主催代办说明，并将中文界面的相关称呼统一为主催。",
      "en": "The upload page now explains artist UID binding and producer proxy submission more clearly, while the Chinese UI uses the producer title consistently."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "提交页说明",
          "en": "Upload guidance"
        },
        "items": [
          {
            "title": {
              "zh-CN": "说明 UID 绑定和主催代办",
              "en": "Explain UID binding and proxy submission"
            },
            "description": {
              "zh-CN": "艺术家区域现在明确提示填写 UID 的平台曲师会拥有曲目并处理曲师侧流程，未填写 UID 的行仅作为外部姓名记录；当本人主催的专辑整首曲目都未绑定 UID 时，后续曲师侧流程由主催代办。",
              "en": "The artist area now states that platform composers with a UID own the track and handle composer-side workflow, while rows without a UID are external name records. When an album produced by the current user has no UID on any artist row, the producer proxies the later composer-side workflow."
            }
          },
          {
            "title": {
              "zh-CN": "统一主催称呼",
              "en": "Align the Chinese producer title"
            },
            "description": {
              "zh-CN": "中文可见文案和历史更新日志中的相关旧称已统一为主催。",
              "en": "Relevant Chinese user-facing copy and changelog text now use the producer title consistently."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.31",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "收紧匿名曲师显示",
      "en": "Tightens anonymous composer display"
    },
    "summary": {
      "zh-CN": "匿名视图不再把平台内曲师回退显示为用户 ID，匿名编号也已轮换为新版规则。",
      "en": "Anonymous views no longer fall back to platform composer user IDs, and anonymous labels now use the refreshed ID rule."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "隐私显示",
          "en": "Privacy display"
        },
        "items": [
          {
            "title": {
              "zh-CN": "隐藏缺少姓名的曲师 ID",
              "en": "Hide composer IDs without names"
            },
            "description": {
              "zh-CN": "当前端只拿到平台内曲师的用户 ID、没有拿到可展示姓名时，曲目详情不再显示平台内曲师行，避免暴露真实账号线索。",
              "en": "When the frontend only receives platform composer user IDs without displayable names, track details no longer render the platform composer row."
            }
          },
          {
            "title": {
              "zh-CN": "轮换匿名编号",
              "en": "Refresh anonymous labels"
            },
            "description": {
              "zh-CN": "同行评审等匿名场景使用新版前端匿名编号，同一用户仍保持全站一致，但旧编号会被替换。",
              "en": "Anonymous peer-review labels now use the refreshed frontend hash. The same user remains consistent across the app, while old labels are replaced."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.30",
    "date": "2026-07-05",
    "headline": {
      "zh-CN": "修复母带页漏翻译文案",
      "en": "Fixes missing mastering-page translations"
    },
    "summary": {
      "zh-CN": "母带交付和终审页面现在会显示正常的交付说明、交付类型和曲师标签，不再暴露翻译键名。",
      "en": "Master delivery and final-review pages now show proper delivery notes, delivery type, and composer labels instead of raw translation keys."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "母带流程",
          "en": "Mastering workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "补齐母带交付文案",
              "en": "Master delivery copy is complete"
            },
            "description": {
              "zh-CN": "母带交付输入框、交付版本历史和终审审批状态现在都会显示对应的中英文文案。",
              "en": "The delivery input, delivery version history, and final-review approval status now show localized copy in both languages."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.29",
    "date": "2026-06-10",
    "headline": {
      "zh-CN": "修复 Checklist 设置重启恢复开启",
      "en": "Fixes checklist settings after backend restarts"
    },
    "summary": {
      "zh-CN": "后端启动时的历史数据填充会保留已关闭的专辑和社团 Checklist 设置，避免部署或重启后又恢复为开启。",
      "en": "Backend startup backfill now preserves disabled album and circle checklist settings, preventing deploys or restarts from turning them back on."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "专辑设置",
          "en": "Album settings"
        },
        "items": [
          {
            "title": {
              "zh-CN": "关闭的 Checklist 会保持关闭",
              "en": "Disabled checklists stay disabled"
            },
            "description": {
              "zh-CN": "启动兼容逻辑只会补齐缺失的旧数据空值，不再覆盖主催已经关闭的专辑 Checklist 和社团默认 Checklist。",
              "en": "Startup compatibility logic now only fills missing legacy null values and no longer overwrites album checklist or circle default checklist settings that producers already disabled."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.28",
    "date": "2026-06-10",
    "headline": {
      "zh-CN": "艺术家绑定改为手填 UID",
      "en": "Artist binding now uses manual UID entry"
    },
    "summary": {
      "zh-CN": "曲目提交页的艺术家账号绑定从账号下拉改为手动填写 UID，第一行默认填入当前登录用户 UID，并允许绑定任意活跃平台用户。",
      "en": "The track upload page now binds artist aliases by manually entering a UID, prefills the first row with the current user's UID, and allows any active platform user to be bound."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "提交页",
          "en": "Upload page"
        },
        "items": [
          {
            "title": {
              "zh-CN": "手动填写绑定账号 UID",
              "en": "Manual UID entry for bound accounts"
            },
            "description": {
              "zh-CN": "每个艺术家名义现在可以直接填写平台用户 UID；第一行会默认填入当前登录用户 UID，留空则继续作为未绑定账号的姓名记录。",
              "en": "Each artist alias can now include a platform user UID directly. The first row is prefilled with the current user's UID, and leaving it blank keeps the row as a name-only credit."
            }
          },
          {
            "title": {
              "zh-CN": "可绑定任意活跃平台用户",
              "en": "Bind any active platform user"
            },
            "description": {
              "zh-CN": "UID 只要求对应用户存在且未封禁、未删除。被绑定用户会拥有该曲目，但不会自动加入专辑成员列表。",
              "en": "A UID only needs to belong to an existing user who is not suspended or deleted. Bound users own the track, but are not automatically added as album members."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.27",
    "date": "2026-06-09",
    "headline": {
      "zh-CN": "母带打回可选择素材类型",
      "en": "Mastering revision requests can choose the material type"
    },
    "summary": {
      "zh-CN": "母带师在母带工作台打回曲目时，现在会先选择需要曲师重新提交源音频，还是提供分轨文件链接；曲师修订页也会锁定对应提交方式。",
      "en": "When a mastering engineer requests a revision from the mastering workspace, they can choose whether the composer should re-upload source audio or provide stem files, and the composer revision page now locks to that method."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "母带流程",
          "en": "Mastering workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "补上母带工作台的打回选项",
              "en": "Revision type selection in the mastering workspace"
            },
            "description": {
              "zh-CN": "在母带工作台点击请求修订时，会弹出源音频修订与分轨文件两种选项，并把选择同步到后续曲师上传流程。",
              "en": "Clicking Request Revision in the mastering workspace now opens the source-audio versus stem-file choice and carries that choice into the composer upload flow."
            }
          },
          {
            "title": {
              "zh-CN": "曲师只能按请求类型提交",
              "en": "Composer submissions follow the requested type"
            },
            "description": {
              "zh-CN": "如果母带师请求源音频，曲师页只显示音频上传；如果请求分轨文件，曲师页只显示网盘链接提交，避免提交到错误类型。",
              "en": "If source audio was requested, the composer only sees audio upload. If stem files were requested, they only see the cloud-link form, preventing the wrong submission type."
            }
          },
          {
            "title": {
              "zh-CN": "母带沟通显示分轨交接",
              "en": "Stem handoff is visible in mastering communication"
            },
            "description": {
              "zh-CN": "曲师提交分轨网盘链接后，母带沟通页会在讨论上方显示当前分轨交接内容，并提供打开链接和复制内容操作。",
              "en": "After the composer submits a stem cloud link, the mastering communication tab now shows the current stem handoff above the discussion thread with actions to open the link or copy the full content."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "提交页",
          "en": "Upload page"
        },
        "items": [
          {
            "title": {
              "zh-CN": "修复平台内曲师文案",
              "en": "Fixed platform composer labels"
            },
            "description": {
              "zh-CN": "曲目提交页的平台内曲师标题和说明现在会正常显示，不再出现 i18n key。",
              "en": "The platform composer title and hint on the track upload page now render as localized text instead of raw i18n keys."
            }
          },
          {
            "title": {
              "zh-CN": "艺术家名义可绑定平台账号",
              "en": "Artist aliases can be bound to platform accounts"
            },
            "description": {
              "zh-CN": "曲目提交页将艺术家名义和平台账号绑定合并到同一个列表：每个名义可手动选择对应账号，同一账号可使用多个名义；未绑定账号的名义作为外部曲师记录，若整首曲目都未绑定账号则由主催代办后续曲师侧流程。",
              "en": "The upload page now keeps artist aliases and platform-account binding in one list: each alias can be manually linked to an account, one account can use multiple aliases, and unlinked aliases are recorded as external composers. If the whole track has no linked account, the producer handles later composer-side workflow."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.26",
    "date": "2026-06-08",
    "headline": {
      "zh-CN": "曲目支持多个外部曲师",
      "en": "Tracks now support multiple external composers"
    },
    "summary": {
      "zh-CN": "提交曲目时可以同时记录平台内曲师和不使用平台的外部曲师。没有平台内曲师的曲目由主催代办曲师侧流程，有平台内曲师时则由任一平台内曲师处理。",
      "en": "Track submissions can now list both platform composers and external composers who do not use the platform. External-only tracks are handled by the producer, while tracks with platform composers let any platform composer handle composer-side work."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "外部曲师",
          "en": "External composers"
        },
        "items": [
          {
            "title": {
              "zh-CN": "提交页可记录多个外部曲师",
              "en": "Submit multiple external composers"
            },
            "description": {
              "zh-CN": "上传曲目时可添加多个外部曲师姓名，并继续从专辑成员中选择平台内共同曲师；曲目详情、流程页和母带页会分别展示两类曲师。",
              "en": "The upload page now accepts multiple external composer names alongside platform co-composers selected from album members. Track details, workflow pages, and mastering pages show both groups separately."
            }
          },
          {
            "title": {
              "zh-CN": "外部-only 曲目由主催代办",
              "en": "Producer proxy for external-only tracks"
            },
            "description": {
              "zh-CN": "当曲目没有平台内曲师时，主催可以代办修订上传、源音频补交、公开问题状态处理和终审确认；外部曲师不会进入评审分配池或接收系统通知。",
              "en": "When a track has no platform composers, the producer can handle revisions, source follow-ups, public issue actions, and final approval on their behalf. External composers are not added to reviewer pools or notification recipients."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.25",
    "date": "2026-06-07",
    "headline": {
      "zh-CN": "曲目支持共同曲师",
      "en": "Tracks now support co-composers"
    },
    "summary": {
      "zh-CN": "提交曲目时可以选择专辑成员作为共同曲师。共同曲师会在曲目列表与详情中显示，并可参与源文件修订、问题状态处理、母带终审确认等曲师侧流程。",
      "en": "Track submissions can now include album members as co-composers. Co-composers appear in track lists and details and can take the composer-side actions for source revisions, issue status updates, and final master approval."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "共同曲师",
          "en": "Co-composers"
        },
        "items": [
          {
            "title": {
              "zh-CN": "提交时选择共同创作者",
              "en": "Select collaborators during submission"
            },
            "description": {
              "zh-CN": "曲目提交页新增共同曲师选择区，当前账号会自动加入，额外选择的专辑成员会一起获得曲师侧可见性和操作权限。",
              "en": "The submit-track page now includes a co-composer selector. The current account is included automatically, and selected album members receive composer-side visibility and permissions."
            }
          },
          {
            "title": {
              "zh-CN": "曲师侧流程同步扩展",
              "en": "Composer-side workflow access expands"
            },
            "description": {
              "zh-CN": "共同曲师现在可以查看私有曲目、处理公开问题状态、上传修订源文件、申请源音频补交，并参与母带终审确认；评审分配会自动避开所有曲师。",
              "en": "Co-composers can now view private tracks, handle public issue status, upload revised source audio, request source follow-ups, and participate in final master approval. Reviewer assignment avoids every composer on the track."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.24",
    "date": "2026-06-07",
    "headline": {
      "zh-CN": "母带修订支持提交分轨链接",
      "en": "Mastering revisions now support stem links"
    },
    "summary": {
      "zh-CN": "当母带阶段需要曲师补充分轨或多轨工程时，曲师可以在母带修订步骤提交网盘链接、提取码和说明；该记录会进入源版本历史，同时保留当前可播放的源音频。母带交付仍需上传母带音频文件。",
      "en": "When mastering needs stems or multitracks from the composer, the composer can submit a cloud link, access code, and notes during the mastering revision step. The entry is kept in source-version history while the current playable source audio stays unchanged. Master delivery still requires an audio file."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "母带修订",
          "en": "Mastering Revision"
        },
        "items": [
          {
            "title": {
              "zh-CN": "曲师可提交分轨 / 多轨网盘链接",
              "en": "Composers can submit stem or multitrack links"
            },
            "description": {
              "zh-CN": "母带师将曲目打回母带修订后，曲师除了上传新的源音频，也可以填写分轨包网盘链接、提取码和处理说明，并把流程送回母带阶段。",
              "en": "After the mastering engineer sends a track to mastering revision, the composer can either upload a revised source file or submit a stem-package cloud link, access code, and handling notes before returning the track to mastering."
            }
          },
          {
            "title": {
              "zh-CN": "当前源音频保持可播放",
              "en": "The current source audio remains playable"
            },
            "description": {
              "zh-CN": "分轨链接会作为新的源版本历史记录保存，但不会覆盖曲目的源音频文件、存储位置或时长；母带交付入口也恢复为必须上传可播放母带音频文件。",
              "en": "A stem-link submission is saved as a new source-version history entry, but it does not overwrite the track's source audio file, storage backend, or duration. Master delivery is again limited to playable mastered audio uploads."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.23",
    "date": "2026-05-30",
    "headline": {
      "zh-CN": "让曲目问题详情可以边看边听",
      "en": "Keeps track issue details playable in context"
    },
    "summary": {
      "zh-CN": "这次更新强化了曲目详情页的问题抽屉：定位到带时间点的问题时，可以直接在详情里预览并控制对应波形；窄屏设备会改用当前页底部展开的面板。",
      "en": "This update improves the track-detail issue drawer: timed issues can preview and control the matching waveform directly inside the detail panel, and narrow screens now use an in-page bottom sheet."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "曲目问题处理",
          "en": "Track Issue Handling"
        },
        "items": [
          {
            "title": {
              "zh-CN": "问题详情里新增紧凑播放预览",
              "en": "Issue details now include a compact playback preview"
            },
            "description": {
              "zh-CN": "点击带时间点的问题或波形标记后，右侧详情抽屉会显示小型波形预览，可播放整个问题、单个标记或拖动定位，终审问题会自动使用当前母带波形。",
              "en": "After opening a timed issue or waveform marker, the right-side detail drawer shows a mini waveform preview for playing the whole issue, playing one marker, or seeking; final-review issues automatically use the current master waveform."
            }
          },
          {
            "title": {
              "zh-CN": "移动端问题详情留在当前页展开",
              "en": "Mobile issue details now expand in place"
            },
            "description": {
              "zh-CN": "窄屏设备点击问题默认从页面底部打开详情面板，不再跳转离开曲目详情；仍可通过兼容开关切回旧版独立问题页。",
              "en": "On narrow screens, clicking an issue now opens a bottom sheet on the track detail page instead of navigating away; the compatibility toggle can still switch back to the legacy standalone issue page."
            }
          },
          {
            "title": {
              "zh-CN": "源音频补交后保留历史未解决问题",
              "en": "Historical unresolved issues stay visible after source-audio follow-ups"
            },
            "description": {
              "zh-CN": "修复源音频补交并进入新流程轮次后，旧版本或旧母带上的未解决问题在列表中消失的问题；这些问题会继续显示在问题列表中，但不会作为标记叠加到当前音频波形上。",
              "en": "Fixed an issue where unresolved issues from an earlier source version or master delivery disappeared from the issue list after a source-audio follow-up moved the track into a new workflow cycle. These issues remain visible in the list, while their markers stay off the current audio waveform."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.22",
    "date": "2026-05-27",
    "headline": {
      "zh-CN": "让仪表盘、通知跳转和曲目问题处理更顺手",
      "en": "Makes dashboard, notification routing, and track issue handling smoother"
    },
    "summary": {
      "zh-CN": "这次 QoL 更新统一了仪表盘状态卡口径、曲目点击落点和通知中心打开路径，并让曲目详情页可以直接处理问题状态与详情。",
      "en": "This QoL update aligns dashboard status-card counts with their filters, unifies track click destinations and notification-center routing, and lets track details handle issue status and detail work in place."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "仪表盘体验",
          "en": "Dashboard Experience"
        },
        "items": [
          {
            "title": {
              "zh-CN": "状态卡筛选现在和数字一致",
              "en": "Status-card filters now match their counts"
            },
            "description": {
              "zh-CN": "同行评审卡会同时显示同行评审和同行修订曲目，母带制作卡会同时显示母带、母带修订和终审曲目；当前筛选也会显示可读标签。",
              "en": "The Peer Flow card now includes both peer review and peer revision tracks, while Mastering Flow includes mastering, mastering revision, and final review tracks. Active filters now show readable labels."
            }
          },
          {
            "title": {
              "zh-CN": "曲目列表点击会直达该处理的工作区",
              "en": "Track-list clicks now open the right workspace"
            },
            "description": {
              "zh-CN": "如果曲目当前有可执行动作，从仪表盘表格或移动卡片打开时会直接进入对应工作流工作区，而不是先落到普通详情页。",
              "en": "When a track has available actions, opening it from the dashboard table or mobile cards now goes straight to the matching workflow workspace instead of the generic detail page."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "曲目处理",
          "en": "Track Handling"
        },
        "items": [
          {
            "title": {
              "zh-CN": "曲目详情页可以直接处理问题",
              "en": "Track details now handle issues in place"
            },
            "description": {
              "zh-CN": "问题列表新增快速状态操作；点击问题卡片或波形标记默认在本页抽屉查看详情、回复和改状态，同时保留可切换回旧版独立问题页的本机偏好。",
              "en": "The issue list now offers quick status actions. Clicking issue cards or waveform markers opens the in-page drawer by default for details, replies, and status changes, while a local preference keeps the legacy standalone issue page available."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "搜索与通知",
          "en": "Search and Notifications"
        },
        "items": [
          {
            "title": {
              "zh-CN": "快速搜索不再被旧结果覆盖",
              "en": "Rapid searches no longer get overwritten by stale results"
            },
            "description": {
              "zh-CN": "仪表盘和专辑列表现在会忽略过期响应；专辑搜索也加入短暂防抖，减少连续输入时的请求和闪烁。",
              "en": "Dashboard and album lists now ignore stale responses, and album search uses a short debounce to reduce request noise and visual flicker while typing."
            }
          },
          {
            "title": {
              "zh-CN": "通知中心与顶部铃铛跳转一致",
              "en": "Notification Center routing now matches the header bell"
            },
            "description": {
              "zh-CN": "带曲目上下文的通知会优先打开对应工作流位置，并携带相关问题定位；只有纯问题通知才会进入独立问题页。",
              "en": "Notifications with track context now open the corresponding workflow location and carry the related issue target. Issue-only notifications still open the standalone issue page."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.21",
    "date": "2026-05-20",
    "headline": {
      "zh-CN": "补上更多失败提示与确认提示",
      "en": "Adds clearer feedback for failed and pending actions"
    },
    "summary": {
      "zh-CN": "通知、投稿、模板、评论、工作流与设置等页面现在会把失败、等待和高风险操作明确提示给用户，减少静默失败。",
      "en": "Notifications, submissions, templates, comments, workflow actions, and settings now surface failures, waiting states, and high-risk actions more clearly."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "用户提示",
          "en": "User Feedback"
        },
        "items": [
          {
            "title": {
              "zh-CN": "失败操作不再静默",
              "en": "Failed actions are no longer silent"
            },
            "description": {
              "zh-CN": "通知加载、标记已读、注册邮件重发、投稿专辑加载、工作流模板加载或保存、评论编辑历史、评论提交和状态更新失败时，会显示行内错误或 toast。",
              "en": "Notification loading and read actions, verification email resend, album loading for submissions, workflow template loading or saving, comment history, comment submission, and issue status updates now show inline errors or toast feedback."
            }
          },
          {
            "title": {
              "zh-CN": "多人审核等待状态会给出反馈",
              "en": "Multi-review waiting states now acknowledge the action"
            },
            "description": {
              "zh-CN": "当工作流操作已提交但还需要等待其他必要审核人完成时，页面会显示成功提示，避免误以为按钮没有生效。",
              "en": "When a workflow action is accepted but the stage still waits for other required reviewers, the page now shows a success message instead of appearing unchanged."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "操作确认",
          "en": "Action Confirmation"
        },
        "items": [
          {
            "title": {
              "zh-CN": "危险操作增加确认或结果反馈",
              "en": "Risky actions now ask for confirmation or show results"
            },
            "description": {
              "zh-CN": "重置专辑检查清单模板、撤销社团邀请码、测试 Webhook、创建社团后上传 Logo 失败、重新分配审核人后刷新失败等流程现在都有明确提示。",
              "en": "Resetting album checklist templates, revoking circle invite codes, testing webhooks, failed logo upload after circle creation, and failed assignment refresh after reviewer reassignment now provide explicit feedback."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.20",
    "date": "2026-05-19",
    "headline": {
      "zh-CN": "修复专辑设置保存时清空资料的问题",
      "en": "Fixes album metadata being cleared from settings saves"
    },
    "summary": {
      "zh-CN": "修复了在专辑设置中只保存部分选项时，简介、发行日期、目录编号、社团名和曲风标签可能被清空的问题。",
      "en": "Fixes an issue where saving a partial album setting could clear description, release date, catalog number, circle name, and genre tags."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "专辑设置",
          "en": "Album Settings"
        },
        "items": [
          {
            "title": {
              "zh-CN": "部分保存不再覆盖专辑资料",
              "en": "Partial saves no longer overwrite album metadata"
            },
            "description": {
              "zh-CN": "保存检查清单模式或源音频补交开关时，系统现在只更新当前提交的设置，不会把未修改的专辑资料写空。",
              "en": "When saving checklist mode or the source follow-up switch, the system now updates only the submitted setting and preserves unchanged album metadata."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.19",
    "date": "2026-05-19",
    "headline": {
      "zh-CN": "新增源音频补交申请",
      "en": "Adds source follow-up requests"
    },
    "summary": {
      "zh-CN": "专辑现在可以选择开启 quick follow-up。开启后，曲师可在非修订阶段上传新的源音频作为待审批申请，主催或相关母带师审批后再替换当前源文件并返回指定流程阶段。",
      "en": "Albums can now opt in to quick follow-up. When enabled, composers can upload a pending source file outside revision stages, and the producer or relevant mastering engineer can approve it before it replaces the current source and returns the track to a selected workflow stage."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "曲目流程",
          "en": "Track Workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "曲师可提交待审批源音频",
              "en": "Composers can submit pending source audio"
            },
            "description": {
              "zh-CN": "专辑设置新增源音频补交开关。开启后，曲师可在曲目详情页上传新的源文件并填写原因；审批前曲目会进入待处理状态，常规流程操作暂时暂停。",
              "en": "Album settings now include a source follow-up switch. Once enabled, composers can upload a new source file and reason from track detail; while it is pending, the track enters a paused follow-up state."
            }
          },
          {
            "title": {
              "zh-CN": "审批时选择返回阶段",
              "en": "Approvers choose the return stage"
            },
            "description": {
              "zh-CN": "主催可批准并选择返回到首个母带交付前的阶段；母带师只能批准到母带相关阶段。批准后新源文件立即成为当前版本，旧母带不再作为当前交付物。",
              "en": "Producers can approve and choose a stage at or before the first delivery step, while mastering engineers can approve only mastering-related targets. Approval immediately makes the uploaded source current, and older masters stop counting as the current delivery."
            }
          },
          {
            "title": {
              "zh-CN": "阶段转换不再自动结案待讨论问题",
              "en": "Pending-discussion issues stay pending across stage changes"
            },
            "description": {
              "zh-CN": "流程进入下一阶段或修订阶段时，待讨论问题会继续保持待讨论状态，不再自动转为内部结案，便于评审组后续发布、处理或继续讨论。",
              "en": "When a workflow advances or enters revision, pending-discussion issues now remain pending instead of being automatically marked internally resolved, so reviewers can publish, resolve, or continue discussing them later."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.18",
    "date": "2026-05-19",
    "headline": {
      "zh-CN": "优化问题公开、曲目提交与母带沟通",
      "en": "Improves issue publishing, track submission, and mastering communication"
    },
    "summary": {
      "zh-CN": "新建问题现在默认公开，同行评审组可以共同公开待讨论或内部结案的问题；代传曲目入口仅对对应专辑主催开放，母带沟通侧边栏也新增全屏查看模式。",
      "en": "New issues now default to public visibility, peer-review groups can publish pending or internally resolved issues together, proxy track submission is limited to the album producer, and the mastering communication sidebar can expand to full screen."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "曲目提交",
          "en": "Track Submission"
        },
        "items": [
          {
            "title": {
              "zh-CN": "代传入口仅对专辑主催开放",
              "en": "Proxy upload is producer-only"
            },
            "description": {
              "zh-CN": "上传曲目时，只有当前所选专辑的主催可以看到并操作“为未使用系统的曲师代传”；切换到非本人主催的专辑会自动清除代传状态。",
              "en": "On the upload page, only the producer of the selected album can see and use the proxy submission option. Switching to an album produced by someone else clears any proxy state."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "问题协作",
          "en": "Issue Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新建问题默认公开",
              "en": "New issues default to public"
            },
            "description": {
              "zh-CN": "在同行评审和母带问题创建面板中，问题默认会公开给曲师；评审人仍可手动切换为仅内部讨论。",
              "en": "Issue creation panels in peer review and mastering now default to public visibility for the submitter, while reviewers can still switch an issue to internal discussion when needed."
            }
          },
          {
            "title": {
              "zh-CN": "评审组可共同公开内部问题",
              "en": "Reviewers can publish internal issues together"
            },
            "description": {
              "zh-CN": "待讨论和内部结案的问题不再只能由原作者公开；同一评审阶段的任一评审人都可以将其发布为公开问题。",
              "en": "Pending-discussion and internally resolved issues no longer require the original author to publish them. Any reviewer assigned to the same review stage can make them public."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "母带沟通",
          "en": "Mastering Communication"
        },
        "items": [
          {
            "title": {
              "zh-CN": "侧边栏新增全屏模式",
              "en": "Sidebar adds a full-screen mode"
            },
            "description": {
              "zh-CN": "母带沟通抽屉顶部新增全屏/退出全屏按钮，便于查看较长的沟通线程和附件。",
              "en": "The mastering communication drawer now has an expand/collapse button in the header, making longer threads and attachments easier to review."
            }
          },
          {
            "title": {
              "zh-CN": "@ 候选列表会向上展开",
              "en": "@ mention suggestions open upward"
            },
            "description": {
              "zh-CN": "在母带沟通底部输入 @ 人员时，候选列表会显示在输入框上方，不再被下方空间挤出视线。",
              "en": "When typing @ people in the bottom-docked mastering chat input, the suggestion list opens above the text area instead of below it."
            }
          },
          {
            "title": {
              "zh-CN": "Issue 面包屑可返回曲目",
              "en": "Issue breadcrumbs link back to the track"
            },
            "description": {
              "zh-CN": "从单个 Issue 详情页查看问题时，顶部面包屑会显示所属曲目，并可直接返回该曲目详情。",
              "en": "Standalone issue detail pages now show the parent track in the breadcrumb trail so users can return directly to the track detail page."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.17",
    "date": "2026-05-19",
    "headline": {
      "zh-CN": "协作与曲目提交流程增强",
      "en": "Collaboration and track submission improvements"
    },
    "summary": {
      "zh-CN": "本次更新加入主催代传外部曲师曲目的流程，支持在评论入口 @ 人协作，并优化问题状态与管理后台的曲目救援操作，减少不必要的必填原因。",
      "en": "This update adds producer proxy uploads for external composers, supports @ mentions in comment entry points, and streamlines issue status changes plus admin track rescue operations by removing unnecessary required reasons."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "曲目提交",
          "en": "Track Submission"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新增主催代传模式",
              "en": "New producer proxy submission mode"
            },
            "description": {
              "zh-CN": "在主催自己的专辑上传曲目时，可以开启「为未使用系统的曲师代传」，填写外部曲师名后提交。曲目详情、审核工作台和母带页面会显示外部曲师与代传主催。",
              "en": "When uploading to their own album, producers can enable external-composer proxy submission and enter the external composer's name. Track detail, workflow, and mastering pages now show the external composer and proxy producer."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "管理后台",
          "en": "Admin Console"
        },
        "items": [
          {
            "title": {
              "zh-CN": "曲目工作流操作的原因改为选填",
              "en": "Track workflow action reasons are now optional"
            },
            "description": {
              "zh-CN": "曲目救援区的原因输入框已标记为选填；留空时系统不再自动写入默认文案，审计记录会保留为空原因。",
              "en": "The reason field in the track rescue area is now marked optional. Leaving it blank no longer inserts default copy, and audit entries keep the reason empty."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "协作",
          "en": "Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "所有评论入口支持 @ 人",
              "en": "All comment entry points support @ people"
            },
            "description": {
              "zh-CN": "在讨论、母带沟通、问题回复、问题状态备注和问题创建描述中输入 @、@姓名、@user、@user: 或 @user:数字会弹出当前上下文可见参与者列表；@user:数字会按用户 ID 前缀过滤。支持方向键、Enter/Tab、Esc 和鼠标选择。内部 issue 不会向曲师暴露候选人，也不会因为 @ 通知曲师。",
              "en": "Typing @, @name, @user, @user:, or @user:digits in discussions, mastering communication, issue replies, issue status notes, and issue descriptions opens the participant picker for that context; @user:digits filters by user ID prefix. Arrow-key, Enter/Tab, Escape, and mouse selection are supported. Internal issues do not expose submitters as candidates and do not notify submitters through mentions."
            }
          },
          {
            "title": {
              "zh-CN": "提及显示为人员 chip",
              "en": "Mentions render as person chips"
            },
            "description": {
              "zh-CN": "系统会把选中的用户保存为 @user:ID，普通用户无需手动输入 ID；阅读时会显示为 @显示名 chip。无权访问或已不可用的用户引用会以不可用样式显示，避免误以为通知仍然有效。",
              "en": "Selected users are stored as @user:ID so regular users do not need to know IDs manually; when reading, they appear as @display-name chips. References to unavailable or unauthorized users render with an unavailable style so stale mentions are not mistaken for active notifications."
            }
          },
          {
            "title": {
              "zh-CN": "问题状态变更说明改为选填",
              "en": "Issue status-change notes are now optional"
            },
            "description": {
              "zh-CN": "主催和曲师在将问题标记为已解决、有异议、待讨论、重新打开或内部结案时，可以直接提交状态变更；说明和附件仍可补充，但不再是必填项。",
              "en": "Producers and composers can now submit issue status changes such as resolved, disagreed, pending discussion, reopened, or internally resolved without a required note. Notes and attachments remain available when extra context is needed."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.16",
    "date": "2026-05-12",
    "headline": {
      "zh-CN": "修正最近更新的审核跳转",
      "en": "Fixes recent-update review navigation"
    },
    "summary": {
      "zh-CN": "Dashboard 顶部的「最近更新」现在会按当前用户权限打开曲目：有待处理动作时进入对应审核工作台，没有动作权限时只打开普通曲目详情页。",
      "en": "The Dashboard recent-updates panel now opens tracks according to the current user's permissions: tracks with pending actions still open the review workspace, while tracks without action permission open the normal track detail page."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "Dashboard",
          "en": "Dashboard"
        },
        "items": [
          {
            "title": {
              "zh-CN": "最近更新不再误入审核界面",
              "en": "Recent updates no longer open review pages incorrectly"
            },
            "description": {
              "zh-CN": "没有审核动作权限的用户点击「最近更新」里的曲目时，会停留在曲目详情上下文，不再跳转到该曲目的审核阶段页面。",
              "en": "When users without review action permission click a track in Recent Updates, they now land in the track detail context instead of being sent to that track's review-stage page."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.15",
    "date": "2026-05-11",
    "headline": {
      "zh-CN": "新增亮色主题与同行评审快速返修模式",
      "en": "Adds a light theme and expedited peer-review revision mode"
    },
    "summary": {
      "zh-CN": "Back Kitchen 现在保留默认暗色外观，同时新增可切换的亮色主题；主催也可以在工作流中开启“任一评审打回即返修”模式，让评审人把建议打回和直接要求重新上传分开处理。",
      "en": "Back Kitchen now keeps the dark theme as the default while adding a switchable light theme. Producers can also enable an “any reviewer can request re-upload” workflow mode so reviewers can separate revision recommendations from direct re-upload requests."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "界面主题",
          "en": "Interface theme"
        },
        "items": [
          {
            "title": {
              "zh-CN": "可在暗色与亮色之间切换",
              "en": "Switch between dark and light"
            },
            "description": {
              "zh-CN": "页头和登录相关页面新增主题按钮；亮色主题使用暖白背景、浅灰分层和橙色主操作，便于在明亮环境中预览和审核。",
              "en": "The header and auth pages now include a theme button. The light theme uses warm off-white backgrounds, soft dividers, and orange primary actions for brighter review environments."
            }
          },
          {
            "title": {
              "zh-CN": "优化亮色主题状态色和封面占位图",
              "en": "Refines light-theme badges and cover placeholders"
            },
            "description": {
              "zh-CN": "亮色主题下通知、更新徽标、侧栏角标、主按钮、勾选框、波形标注和工作流编辑器的阶段高亮改为更柔和的语义色片；已解决的波形标注不再使用突兀的绿色，专辑进度条改为更明亮但低饱和的图表色。没有上传封面的专辑现在使用随主题变化的浅色唱片占位图。",
              "en": "In the light theme, notification and update badges, sidebar badges, primary buttons, checkboxes, waveform markers, and workflow-editor stage highlights now use softer semantic chips. Resolved waveform markers no longer use the prominent green, while album progress bars use brighter low-saturation chart colors. Albums without covers render a theme-aware placeholder instead of the fixed dark record art."
            }
          },
          {
            "title": {
              "zh-CN": "侧栏新增个人中心入口",
              "en": "Adds a sidebar profile shortcut"
            },
            "description": {
              "zh-CN": "侧栏底部的头像与用户名区域现在可以直接进入个人中心；桌面折叠状态和移动端抽屉中也保持相同入口。",
              "en": "The sidebar avatar and name area now opens the profile page directly, including collapsed desktop and mobile drawer layouts."
            }
          },
          {
            "title": {
              "zh-CN": "移除飞书提及前端配置",
              "en": "Removes Feishu mention setup from the frontend"
            },
            "description": {
              "zh-CN": "专辑 Webhook 设置不再显示飞书 App ID、App Secret 与 @ 提及配置；个人资料页也不再显示飞书联系方式字段。",
              "en": "Album webhook settings no longer show Feishu App ID, App Secret, or @mention setup fields, and profile settings no longer show the Feishu contact field."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "建议打回和直接返修分开处理",
              "en": "Revision recommendations and direct re-upload are now separate"
            },
            "description": {
              "zh-CN": "开启新模式后，评审人可以先记录“建议打回”，也可以确认后直接让曲目进入修订阶段。未完成的内部待讨论 issue 不会自动结案，仍可由评审组继续处理或发布给曲师。",
              "en": "When the new mode is enabled, reviewers can record a revision recommendation first or confirm a direct move into revision. Unfinished internal discussion issues are no longer auto-closed and can still be handled by the review group or published to the submitter."
            }
          },
          {
            "title": {
              "zh-CN": "工作流编辑器说明随模式切换",
              "en": "Workflow editor hints now follow the selected mode"
            },
            "description": {
              "zh-CN": "返修触发方式在“达到人数后统一决定”和“任一评审打回即返修”之间切换时，下方说明会同步解释当前模式的实际行为。",
              "en": "When switching the revision trigger between quorum-based decisions and immediate re-upload requests, the helper text now explains the currently selected behavior."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.14",
    "date": "2026-05-11",
    "headline": {
      "zh-CN": "修复重复评审分配显示",
      "en": "Fixes duplicate review assignment display"
    },
    "summary": {
      "zh-CN": "同一评审人在同一评审阶段不会再因为历史分配被重复计数；曲目摘要会按当前有效评审人去重显示，并且后端会阻止新的重复有效分配。",
      "en": "The same reviewer is no longer counted multiple times within one review stage. Track summaries now display current active reviewers once, and the backend prevents new duplicate active assignments."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评审人列表按当前有效分配去重",
              "en": "Reviewer lists now dedupe active assignments"
            },
            "description": {
              "zh-CN": "重新进入同行评审或管理员重新分配评审人时，旧的有效分配会被正确关闭；已有重复记录会在迁移中标记为已取代，不会再把同一评审人显示为多个人。",
              "en": "When a track re-enters peer review or an administrator reassigns reviewers, older active assignments are closed correctly. Existing duplicate records are marked as superseded by the migration so one reviewer no longer appears as multiple reviewers."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.13",
    "date": "2026-05-11",
    "headline": {
      "zh-CN": "修复波形音频偶发加载失败",
      "en": "Fixes intermittent waveform audio loading failures"
    },
    "summary": {
      "zh-CN": "波形播放器现在会直接使用已缓存的音频数据，不再让 Wavesurfer 重新抓取浏览器内部的 blob 地址，减少偶发的 Failed to fetch 播放失败。",
      "en": "The waveform player now loads cached audio data directly instead of asking Wavesurfer to fetch browser-internal blob URLs again, reducing intermittent Failed to fetch playback errors."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "音频播放",
          "en": "Audio playback"
        },
        "items": [
          {
            "title": {
              "zh-CN": "减少波形播放器的 Failed to fetch 错误",
              "en": "Reduced Failed to fetch errors in the waveform player"
            },
            "description": {
              "zh-CN": "当前源音频、版本对比和下载音频都会复用同一份缓存数据；播放器会直接读取 Blob 内容，避免对 blob: 地址进行第二次 fetch。",
              "en": "Current source audio, version comparison, and downloads now reuse the same cached data. The player reads Blob contents directly, avoiding a second fetch of blob: URLs."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.12",
    "date": "2026-05-11",
    "headline": {
      "zh-CN": "修复旧评审记录残留问题",
      "en": "Fixes stale review record cleanup"
    },
    "summary": {
      "zh-CN": "删除曲目后，旧的评审分配、播放偏好和通知引用会被正确清理，避免新曲目复用编号时看到不属于自己的历史评审记录。",
      "en": "Deleted tracks now clean up old review assignments, playback preferences, and notification links correctly, preventing reused track IDs from showing unrelated historical review records."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "旧评审分配不会再挂到新曲目上",
              "en": "Old review assignments no longer attach to new tracks"
            },
            "description": {
              "zh-CN": "后端现在会启用 SQLite 外键检查，并在删除曲目前清理会阻塞删除或造成误关联的引用；迁移也会清除历史数据库中已失效的评审分配和通知链接。",
              "en": "The backend now enables SQLite foreign-key checks and clears references that could block deletion or create false links before a track is removed. The migration also cleans invalid historical review assignments and notification links."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.11",
    "date": "2026-05-10",
    "headline": {
      "zh-CN": "头像刷新后不再显示为坏图",
      "en": "Avatars now keep rendering after refresh"
    },
    "summary": {
      "zh-CN": "修复头像上传成功后刷新页面会从前端站点路径加载图片的问题。头像现在会使用与其他上传资源一致的后端资源地址。",
      "en": "Fixes avatar images loading from the frontend site path after a successful upload. Avatars now use the same backend asset URL handling as other uploaded resources."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "个人资料",
          "en": "Profile"
        },
        "items": [
          {
            "title": {
              "zh-CN": "修复头像上传后的刷新显示",
              "en": "Fixed avatar display after refresh"
            },
            "description": {
              "zh-CN": "个人资料页和侧边栏头像现在会解析到正确的上传资源地址，在前端和后端分开部署时不会再请求错误的 `/uploads` 路径。",
              "en": "Profile and sidebar avatars now resolve to the correct uploaded asset URL, so split frontend/backend deployments no longer request the wrong `/uploads` path."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.10",
    "date": "2026-05-07",
    "headline": {
      "zh-CN": "同行评审页支持快速分配审稿人",
      "en": "Peer review page now supports quick reviewer assignment"
    },
    "summary": {
      "zh-CN": "主催现在可以在同行评审步骤页直接分配或重新分配审稿人，不必返回曲目详情页处理空置的评审阶段。",
      "en": "Producers can now assign or reassign reviewers directly from the peer review step page instead of returning to track details when a review stage is unassigned."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审分配",
          "en": "Review assignment"
        },
        "items": [
          {
            "title": {
              "zh-CN": "主催可在评审协作卡片中分配审稿人",
              "en": "Producers can assign reviewers from the coordination card"
            },
            "description": {
              "zh-CN": "同行评审页的评审协作卡片新增分配入口：手动模式会打开成员选择弹窗，自动或固定评审池则可一键重新触发分配。",
              "en": "The review coordination card now includes an assignment control: manual stages open a member picker, while auto and fixed-pool stages can rerun assignment with one click."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "评论附件",
          "en": "Comment attachments"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评论和问题表单支持直接粘贴图片",
              "en": "Comments and issue forms now accept pasted images"
            },
            "description": {
              "zh-CN": "在问题评论、状态说明、讨论消息和新建问题表单中，可直接从剪贴板粘贴 JPEG、PNG、WebP 或 GIF 图片作为附件。",
              "en": "Issue comments, status notes, discussion messages, and new issue forms now let you paste JPEG, PNG, WebP, or GIF images from the clipboard as attachments."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.9",
    "date": "2026-05-06",
    "headline": {
      "zh-CN": "修复实时连接权限与诊断日志",
      "en": "Fixes real-time connection permissions and diagnostics"
    },
    "summary": {
      "zh-CN": "固定评审池和阶段分配中的评审人现在可以正常建立曲目实时连接；服务器也会记录 WebSocket 握手阶段的异常堆栈，便于排查偶发连接错误。",
      "en": "Reviewers assigned through fixed reviewer pools or stage assignments can now open track real-time connections, and the server records handshake exception traces for easier diagnosis of intermittent connection errors."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "实时协作",
          "en": "Real-time collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评审分配权限同步到 WebSocket",
              "en": "Review assignment permissions now apply to WebSocket access"
            },
            "description": {
              "zh-CN": "曲目实时连接现在与曲目详情页使用一致的可见性规则，固定评审池或阶段分配中的评审人不会再因为旧评审字段为空而被拒绝连接。",
              "en": "Track real-time connections now use the same visibility rules as the track detail page, so fixed-pool and stage-assigned reviewers are no longer rejected when the legacy reviewer field is empty."
            }
          },
          {
            "title": {
              "zh-CN": "握手异常会写入后端日志",
              "en": "Handshake failures now write backend logs"
            },
            "description": {
              "zh-CN": "WebSocket 鉴权和权限检查中的意外异常会记录到后端日志，并按连接错误关闭，避免浏览器只显示 500 而服务器缺少排查线索。",
              "en": "Unexpected errors during WebSocket authentication and access checks are logged on the backend and closed as connection errors, avoiding browser-only 500s without server-side clues."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.8",
    "date": "2026-05-05",
    "headline": {
      "zh-CN": "修复曲目重提与固定评审流程",
      "en": "Fixes track resubmission and fixed-review flows"
    },
    "summary": {
      "zh-CN": "可重新提交的退稿现在能在曲目详情页直接上传新源音频；固定评审允许主催参与同行评审，并修复终审退回母带后的批准状态重置。",
      "en": "Resubmittable rejected tracks can now upload a new source from the detail page. Fixed reviews can include the producer, and final-review returns to mastering now reset approval state correctly."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "工作流",
          "en": "Workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "可重提退稿有了上传入口",
              "en": "Resubmittable rejections now have an upload entry"
            },
            "description": {
              "zh-CN": "当曲目被拒绝但允许重新提交时，曲师可以直接在曲目详情页选择新源音频并回到接收审核阶段。",
              "en": "When a track is rejected with resubmission allowed, the submitter can choose a new source file from the detail page and return the track to intake."
            }
          },
          {
            "title": {
              "zh-CN": "固定评审支持主催参与",
              "en": "Fixed reviews support producer reviewers"
            },
            "description": {
              "zh-CN": "固定评审池现在可以包含主催；系统会按评审分配记录判断权限和计数，提交者本人仍会被排除。",
              "en": "Fixed reviewer pools can include the producer. Permissions and counts follow assignment records, while the track submitter remains excluded."
            }
          },
          {
            "title": {
              "zh-CN": "终审退回母带重置批准状态",
              "en": "Final-review returns reset approval state"
            },
            "description": {
              "zh-CN": "终审退回母带后仍停留在同一工作流轮次内，但会清空当前母带的终审批准状态，后续母带版本继续按交付编号递增。",
              "en": "Returning from final review to mastering stays in the same workflow cycle, clears current master approval state, and keeps later master versions numbered within that cycle."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.7",
    "date": "2026-05-05",
    "headline": {
      "zh-CN": "Webhook 设置新增曲师邮件提醒",
      "en": "Adds composer email reminders to Webhook settings"
    },
    "summary": {
      "zh-CN": "专辑的 Webhook 设置现在可以单独启用曲师邮件提醒。启用后，新的公开问题、公开问题回复，以及退回修订等需要曲师处理的待办，会通过已验证邮箱发送给当前曲目的提交者。",
      "en": "Album Webhook settings can now enable composer email reminders separately. When enabled, new public issues, public issue replies, and revision requests are emailed to the current track submitter's verified email address."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "通知",
          "en": "Notifications"
        },
        "items": [
          {
            "title": {
              "zh-CN": "按专辑启用曲师邮件提醒",
              "en": "Per-album composer email reminders"
            },
            "description": {
              "zh-CN": "制作人可以在专辑的 Webhook 标签页开启「邮件通知曲师」，并选择新公开问题、公开问题回复和请求修订三类触发事件。邮件只发送给对应曲目的提交者，不会写入 Webhook 发送历史。",
              "en": "Producers can enable Email composers from an album's Webhook tab and choose new public issues, public issue replies, and revision requests as triggers. Emails go only to the related track submitter and are kept separate from Webhook delivery history."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.6",
    "date": "2026-05-05",
    "headline": {
      "zh-CN": "新增固定多人评审，并补齐重开与母带确认流程细节",
      "en": "Adds fixed multi-reviewer assignment and tightens reopen and mastering confirmation flows"
    },
    "summary": {
      "zh-CN": "同行评审现在支持自动分配、手动指派和固定多人评审三种模式。固定名单中如果包含投稿者本人，系统会在该曲目中自动排除投稿者；排除后无人可审时会通知主催手动指派。同时修复了直接重开母带备注不保存、母带页重复确认按钮、部分工作流状态文案回退和角色切换时旧请求干扰登录态的问题。",
      "en": "Peer review now supports auto assignment, manual assignment, and fixed multi-reviewer lists. When a fixed list contains the submitter, that person is excluded for their own track; if nobody remains, the producer is notified to assign reviewers manually. This release also fixes direct-reopen mastering notes, duplicate mastering confirmation buttons, missing workflow status labels, and stale requests interfering with newer login state."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "工作流评审",
          "en": "Workflow review"
        },
        "items": [
          {
            "title": {
              "zh-CN": "固定多人评审模式",
              "en": "Fixed multi-reviewer mode"
            },
            "description": {
              "zh-CN": "工作流编辑器新增「固定评审」模式，可为同行评审阶段选择固定评审名单；进入评审时会为所有非投稿者的固定评审人创建待审任务，并要求实际分配到的人全部完成评审。",
              "en": "The workflow editor now has a Fixed reviewers mode for peer review stages. Entering review creates pending assignments for every fixed reviewer who is not the submitter, and all actually assigned reviewers must finish."
            }
          },
          {
            "title": {
              "zh-CN": "自审排除与手动回退",
              "en": "Self-review exclusion and manual fallback"
            },
            "description": {
              "zh-CN": "自动、手动、固定三种模式都继续禁止投稿者审核自己的稿件。固定名单排除投稿者后若无人可审，系统会通知主催手动安排评审。",
              "en": "Auto, manual, and fixed assignment all continue to prevent submitters from reviewing their own tracks. If a fixed list has no reviewer left after excluding the submitter, the producer is notified to assign reviewers manually."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "流程修复",
          "en": "Flow fixes"
        },
        "items": [
          {
            "title": {
              "zh-CN": "直接重开母带阶段会保存备注",
              "en": "Direct mastering reopen now saves notes"
            },
            "description": {
              "zh-CN": "主催直接把已完成曲目重开到母带相关阶段时，弹窗里填写的母带备注现在会同步写回曲目，母带师进入页面即可看到。",
              "en": "When a producer directly reopens a completed track into a mastering-related stage, the mastering notes entered in the dialog are now saved back to the track."
            }
          },
          {
            "title": {
              "zh-CN": "重开同行评审不再重复显示评审人",
              "en": "Reopened peer review no longer duplicates reviewers"
            },
            "description": {
              "zh-CN": "已完成曲目重开到同行评审时，会先清理上一轮的已提交评审任务，再按当前评审模式重新生成待提交列表，避免「评审协作」中出现同一评审人的待提交和已提交重复行。",
              "en": "When a completed track is reopened into peer review, old submitted review tasks are cleared before the current assignment mode rebuilds the pending list, preventing duplicate pending/submitted rows for the same reviewer."
            }
          },
          {
            "title": {
              "zh-CN": "母带确认入口不再重复",
              "en": "Mastering confirmation is no longer duplicated"
            },
            "description": {
              "zh-CN": "母带页保留底部操作栏的确认交付入口，移除了卡片中重复出现的「确认上传无误」按钮。",
              "en": "The mastering page keeps the confirmation action in the bottom action bar and removes the duplicate inline confirm-upload button."
            }
          },
          {
            "title": {
              "zh-CN": "请求和实时连接更稳",
              "en": "Requests and live connections are steadier"
            },
            "description": {
              "zh-CN": "接口重试会重新读取当前 token；旧 token 的 401 不会清掉新登录态。曲目页在路由或登录状态变化时会关闭旧 WebSocket，并忽略旧页面请求的过期结果。",
              "en": "API retries now re-read the current token, and a 401 from an old token no longer clears a newer login. Track pages close stale WebSockets on route or auth changes and ignore outdated page-load results."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.5",
    "date": "2026-04-20",
    "headline": {
      "zh-CN": "补齐多语言覆盖：邮箱验证、重置密码和社团详情页现在会跟随语言切换",
      "en": "Fills in missing translations on email verification, reset password, and circle detail pages"
    },
    "summary": {
      "zh-CN": "过去邮箱验证页整页只有英文、重置密码页的「显示/隐藏密码」无障碍标签总是英文、社团详情页的头像上传按钮和「复制邀请码」无障碍标签也不跟随语言切换；这次把这些遗漏的文案全部接入了多语言系统，切到中文时不会再突兀地冒出英文。",
      "en": "The email verification page used to be English-only, the Show/Hide password aria-label on the reset password page was always English, and the circle detail page's upload-logo button and Copy invite code aria-label ignored the current language. This release routes all of those through the i18n system, so nothing jumps back to English when you're browsing in Chinese."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "多语言修复",
          "en": "Localization fixes"
        },
        "items": [
          {
            "title": {
              "zh-CN": "邮箱验证页整页支持多语言",
              "en": "Email verification page now fully localized"
            },
            "description": {
              "zh-CN": "打开邮箱验证链接后看到的加载、成功、失败三种状态文案，以及「返回登录」按钮和各类错误提示，现在都会按当前语言显示。",
              "en": "The loading, success, and failure copy shown when you open a verification link — plus the Back to sign in button and all error messages — now follow your current language setting."
            }
          },
          {
            "title": {
              "zh-CN": "重置密码页的密码可见性按钮标签",
              "en": "Password visibility toggle on the reset password page"
            },
            "description": {
              "zh-CN": "密码输入框右侧眼睛图标的无障碍标签（屏幕阅读器读出的「显示密码/隐藏密码」）现在会跟随语言切换；链接缺失 token 时的报错也改为多语言文案。",
              "en": "The accessibility label on the eye icon next to the password field (the Show password / Hide password text a screen reader reads) now follows your language, and the missing-token error on that page is translated as well."
            }
          },
          {
            "title": {
              "zh-CN": "社团详情页的头像上传与邀请码复制标签",
              "en": "Circle detail page's upload logo and invite code labels"
            },
            "description": {
              "zh-CN": "社团详情页上传头像按钮、每个邀请码旁「复制」按钮的无障碍标签现在都会按当前语言显示，之前始终是英文。",
              "en": "The upload-logo button and the Copy invite code aria-labels on each invite row now follow your current language; previously both were always English."
            }
          },
          {
            "title": {
              "zh-CN": "专辑设置页的角色标签与保存失败提示",
              "en": "Role label and save-error toast on album settings"
            },
            "description": {
              "zh-CN": "专辑设置页中，管理员身份显示的「Admin」标签、保存工作流失败时的兜底提示，现在都接入了多语言。",
              "en": "On the album settings page, the Admin role badge and the fallback toast shown when saving the workflow fails are now translated."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.4",
    "date": "2026-04-20",
    "headline": {
      "zh-CN": "首页曲目分页、实时连接可重试，以及全站细腻过渡动效",
      "en": "Dashboard pagination, actionable live-connection reconnect, and subtle motion across the app"
    },
    "summary": {
      "zh-CN": "大量曲目的专辑在首页现在分批渲染，列表更流畅；曲目页实时连接断开时会显示重连尝试次数并提供「立即重试」按钮；同时我们在 Toast、弹窗、侧边栏徽标、状态徽章、波形播放器、讨论列表等多处加上了低干扰的过渡动效，整体更顺滑。",
      "en": "Albums with many tracks now render in batches on the dashboard for snappier scrolling. When the track page loses its real-time connection, the banner shows the reconnect attempt count and a Retry now button. On top of that, we've added low-key motion to toasts, modals, sidebar badges, status badges, the waveform player, and discussion lists for an overall smoother feel."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "首页与实时协作",
          "en": "Dashboard & Real-time"
        },
        "items": [
          {
            "title": {
              "zh-CN": "首页曲目列表分批加载",
              "en": "Dashboard track list now loads in batches"
            },
            "description": {
              "zh-CN": "首页曲目表默认显示前 50 首，底部提供「加载更多」按钮并展示当前/总数；切换筛选或搜索会回到初始批次，避免一次渲染上百条造成的卡顿。",
              "en": "The dashboard track table now renders the first 50 tracks and surfaces a Load more button with a visible / total counter. Switching filters or typing in search resets to the initial batch, so big album lists no longer stall the first paint."
            }
          },
          {
            "title": {
              "zh-CN": "实时连接断开时可主动重试",
              "en": "Retry now control on live-connection dropouts"
            },
            "description": {
              "zh-CN": "曲目详情、母带、工作流三处的「实时连接已断开」横幅现在会显示第几次重连尝试，并提供「立即重试」按钮跳过指数退避等待；内部同时修复了一处可能造成双连接的竞态。",
              "en": "The reconnect banner on the track detail, mastering, and workflow pages now shows the current attempt number and offers a Retry now button that skips the exponential-backoff wait. We also patched a race that could briefly open two sockets during manual retry."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "界面质感",
          "en": "Interface polish"
        },
        "items": [
          {
            "title": {
              "zh-CN": "六处界面细节加入轻量过渡",
              "en": "Subtle transitions across six surfaces"
            },
            "description": {
              "zh-CN": "Toast 会从侧边滑入并带邻居挪位动画；通用弹窗背景淡入、面板缩放入场；快捷键面板、侧边栏未读徽标、曲目状态徽章、波形播放器的播放/暂停图标都加入了短促的视觉反馈；聊天和讨论消息列表统一使用一致的上滑入场。",
              "en": "Toasts slide in from the side with neighbors easing into place; the shared modal has a backdrop fade and a scale-in panel; the shortcuts modal, sidebar unread badges, track status badges, and the waveform player's play/pause icon all gained short feedback animations; chat and discussion messages share one slide-up entrance."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.3",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "评论区新增 @issue 问题引用选择器",
      "en": "@issue picker lands in all comment inputs"
    },
    "summary": {
      "zh-CN": "在所有讨论和评论输入框中，输入 @i 即可弹出当前曲目问题的选择器，支持按编号过滤和键盘操作，选中后自动插入 @issue:N 并渲染为可点击的问题链接。",
      "en": "Typing @i in any discussion or comment input now opens a picker of the current track's issues with filter-by-number and full keyboard support. Selecting an item inserts @issue:N, which renders as a clickable issue chip."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评审与协作",
          "en": "Review & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评论区新增 @issue 问题引用选择器",
              "en": "Comment inputs gain an @issue reference picker"
            },
            "description": {
              "zh-CN": "在曲目讨论、母带讨论、母带沟通侧边栏、问题详情评论以及创建问题时的描述框中，输入 @i 即可弹出当前曲目问题列表，继续输入数字可按 local_number 前缀过滤。支持 ↑ ↓ 切换、Enter/Tab 插入、Esc 关闭、鼠标点击；选中后自动补齐为 @issue:N。",
              "en": "Track discussions, mastering discussions, the mastering chat sidebar, issue-detail comment boxes, and the issue creation description box now all surface the same @issue picker. Typing @i opens the list of the current track's issues; additional digits filter by local_number prefix. Arrow keys navigate, Enter/Tab inserts, Escape dismisses, and the selected issue is inserted as @issue:N."
            }
          },
          {
            "title": {
              "zh-CN": "修复：曲目讨论中的引用语法提示从未出现",
              "en": "Fix: reference syntax hint never appeared in track discussions"
            },
            "description": {
              "zh-CN": "之前 DiscussionPanel 的 enableReferencePopover 由于 Vue 可选 boolean 属性默认被规范为 false，导致讨论区从未挂载过语法提示 popover。现在该属性默认值显式为 true，讨论框在输入时间戳、标记或问题引用时都会出现语法提示。",
              "en": "DiscussionPanel's enableReferencePopover was effectively forced to false because Vue normalizes unspecified optional boolean props to false, which meant the reference-syntax popover never mounted inside discussion inputs. The default is now explicitly true, so typing timestamps, marker references, or issue references again surfaces the syntax hint."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.2",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "工作流与评审体验更新",
      "en": "Workflow and review improvements"
    },
    "summary": {
      "zh-CN": "本次更新重点补齐了专辑级 checklist 开关、专辑创建时的审稿人分配默认值、修订上传时的问题批量关闭，以及 discussion 音频在 Cloudflare R2 下的上传链路。",
      "en": "This release focuses on album-level checklist policy controls, reviewer assignment defaults during album creation, issue resolution during revision uploads, and the discussion-audio upload path when Cloudflare R2 is enabled."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "工作流与评审",
          "en": "Workflow & Review"
        },
        "items": [
          {
            "title": {
              "zh-CN": "专辑可单独开启或关闭同行评审 checklist",
              "en": "Albums can now enable or disable the peer-review checklist independently"
            },
            "description": {
              "zh-CN": "社团可以设置新专辑的默认 checklist 策略，专辑创建页和设置页也都可以显式覆盖。关闭后，同行评审界面会立即隐藏 checklist 主工作区并解除对应阻塞。",
              "en": "Circles can define the default checklist policy for new albums, while album creation and album settings can explicitly override it. When disabled, the peer-review workspace hides the checklist UI and removes its blocker immediately."
            }
          },
          {
            "title": {
              "zh-CN": "修订版上传支持批量关闭已处理问题",
              "en": "Revision uploads can now resolve selected issues in one step"
            },
            "description": {
              "zh-CN": "作者上传新源版本时，可以同时提交本次修订已解决的问题和说明备注；系统会在同一事务里写入新版本、更新问题状态并留下状态说明。",
              "en": "When uploading a new source revision, submitters can now include the issues resolved in that revision and an optional note. The system updates the source version, issue statuses, and status-note comments in a single transaction."
            }
          },
          {
            "title": {
              "zh-CN": "同行评审 checklist 草稿会保留并提示重新确认",
              "en": "Peer-review checklist drafts now preserve prior answers and prompt reconfirmation"
            },
            "description": {
              "zh-CN": "如果当前 reviewer 在同一轮工作流中已经提交过上一个源版本的 checklist，系统会自动预填答案，并明确提示这是来自旧版本的内容，需要重新保存确认。",
              "en": "If the current reviewer has already submitted a checklist for a previous source version in the same workflow cycle, the answers are prefilled and clearly marked as needing reconfirmation before the review can be completed."
            }
          },
          {
            "title": {
              "zh-CN": "默认审稿人分配切换不再把工作流标签重置成英文",
              "en": "Changing the default reviewer assignment no longer resets workflow labels to English"
            },
            "description": {
              "zh-CN": "在新建专辑页通过快捷控件切换首个同行评审阶段的自动分配或手动指派时，下面的可视化工作流编辑器现在会保留当前界面的语言标签，不会再突然显示英文步骤名。",
              "en": "When producers switch the first peer-review stage between automatic and manual assignment from the quick control on the new album page, the visual workflow editor now keeps step labels in the current UI language instead of unexpectedly reverting them to English."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "上传与附件",
          "en": "Uploads & Attachments"
        },
        "items": [
          {
            "title": {
              "zh-CN": "discussion 音频补齐了 R2 上传路径",
              "en": "Discussion audio now supports the R2 upload path"
            },
            "description": {
              "zh-CN": "当对象存储开启时，曲目讨论和母带讨论中的音频附件会先请求预签名上传，再把对象 key 提交给后端，和现有评论音频链路保持一致。",
              "en": "When object storage is enabled, audio attachments in both track discussions and mastering discussions now use presigned uploads before submitting object keys back to the backend, matching the existing comment-audio flow."
            }
          },
          {
            "title": {
              "zh-CN": "专辑创建页新增评审默认设置",
              "en": "Album creation now includes review-default controls"
            },
            "description": {
              "zh-CN": "创建专辑时可以直接设置首个同行评审阶段是自动分配还是手动分配审稿人，并且可以同时决定该专辑的 checklist 是否默认开启。",
              "en": "Album creation now lets producers choose whether the first peer-review stage uses automatic or manual reviewer assignment, alongside the album’s default checklist policy."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.1.1",
    "date": "2026-04-17",
    "headline": {
      "zh-CN": "本版本更新概览",
      "en": "Release overview"
    },
    "summary": {
      "zh-CN": "本次更新聚焦专辑封面上传体验，新增 20 MB 专用上限与更清晰的上传提示，且不影响其他图片上传场景。以下为本版本主要变更。",
      "en": "This release focuses on the album cover upload experience, adding a dedicated 20 MB limit and clearer upload feedback without affecting other image upload flows. The key changes in this release are listed below."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "专辑与上传",
          "en": "Albums & Uploads"
        },
        "items": [
          {
            "title": {
              "zh-CN": "专辑封面单独支持最多 20 MB 上传",
              "en": "Album covers now support uploads up to 20 MB"
            },
            "description": {
              "zh-CN": "专辑封面上传改为使用独立的 20 MB 限制，不再复用系统其他图片附件的 10 MB 通用限制；头像、社团 Logo、问题与评论图片等其他上传场景保持原有上限不变。",
              "en": "Album cover uploads now use a dedicated 20 MB limit instead of the shared 10 MB image limit used elsewhere. Other upload flows such as avatars, circle logos, and issue/comment images retain their existing limits."
            }
          },
          {
            "title": {
              "zh-CN": "优化专辑封面上传校验与报错提示",
              "en": "Improved album cover validation and error feedback"
            },
            "description": {
              "zh-CN": "在新建专辑页与专辑设置页中，封面选择阶段会提前校验格式与大小，并对常见上传失败原因给出更明确的提示；若专辑已创建但封面上传失败，也会明确说明后续需要在设置页重新上传。",
              "en": "The new album and album settings pages now validate cover format and size before upload and provide clearer messages for common upload failures. If album creation succeeds but the cover upload fails, the UI now explicitly tells the user to re-upload the cover in album settings."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.0.2",
    "date": "2026-04-18",
    "headline": {
      "zh-CN": "通知与评审体验优化",
      "en": "Notification and Review Workflow Polish"
    },
    "summary": {
      "zh-CN": "本次更新重点优化了评论与工作流通知的上下文信息和提示文案，并收紧了评审内部问题的公开权限，减少误通知与误公开。",
      "en": "This release focuses on clearer context and copy in comment and workflow notifications, while tightening publication rules for reviewer-only issues to reduce accidental alerts and unintended exposure."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "通知与协作",
          "en": "Notifications & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "评论通知现在会显示更完整的上下文",
              "en": "Comment notifications now include fuller context"
            },
            "description": {
              "zh-CN": "评论相关的飞书 / Webhook 通知现在会显示对应曲目、问题上下文和操作人，群消息里更容易判断是哪首曲子、哪条问题发生了新的互动。",
              "en": "Feishu and webhook notifications for comments now include the related track, issue context, and actor, making it much easier to tell which track and which issue a new interaction belongs to at a glance."
            }
          },
          {
            "title": {
              "zh-CN": "修复评论通知偶发重复发送",
              "en": "Fixed occasional duplicate comment notifications"
            },
            "description": {
              "zh-CN": "修复了同一条评论在外部通知渠道中偶发重复推送的问题，避免群内短时间收到两条内容相同的提醒。",
              "en": "Fixed an issue where the same comment could occasionally be pushed twice through external notification channels, avoiding back-to-back duplicate alerts in group chats."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "评审流程",
          "en": "Review Workflow"
        },
        "items": [
          {
            "title": {
              "zh-CN": "自动流程通知文案更清晰",
              "en": "Automatic workflow notifications are clearer"
            },
            "description": {
              "zh-CN": "需要手动指派评审人、评审重新开启、内部讨论问题自动结案、同行评审人数达标等自动通知已改为更清晰的表述，并会显示触发本次流程推进的操作人。",
              "en": "Automatic notifications for manual reviewer assignment, reopened reviews, automatic closure of internal-discussion issues, and peer-review quorum now use clearer wording and show who triggered the workflow progression."
            }
          },
          {
            "title": {
              "zh-CN": "收紧评审内部问题的公开权限",
              "en": "Publishing reviewer-only issues is now more restricted"
            },
            "description": {
              "zh-CN": "处于“待讨论”或“内部结案”状态的问题，现在只有问题创建者可以重新发布为公开问题，避免其他评审误将仅内部可见的问题暴露给曲师。",
              "en": "Issues in \"pending discussion\" or \"internally resolved\" states can now only be republished as public issues by their original author, preventing other reviewers from accidentally exposing reviewer-only content to submitters."
            }
          }
        ]
      }
    ]
  },
  {
    "version": "0.0.1",
    "date": "2026-04-17",
    "headline": {
      "zh-CN": "本版本更新概览",
      "en": "Release overview"
    },
    "summary": {
      "zh-CN": "本次更新涵盖评论协作、后台管理、工作流与仪表盘、母带阶段、专辑导出、下载与播放以及安全性等多个方面，包含若干项功能新增、体验优化与问题修复。以下为本版本主要变更。",
      "en": "This release covers comment collaboration, admin management, workflow and dashboard, the mastering stage, album export, downloads and playback, and safety, comprising a number of new features, experience improvements, and bug fixes. The key changes in this release are listed below."
    },
    "sections": [
      {
        "heading": {
          "zh-CN": "评论与协作",
          "en": "Comments & Collaboration"
        },
        "items": [
          {
            "title": {
              "zh-CN": "优化讨论区加载表现",
              "en": "Improved discussion panel loading"
            },
            "description": {
              "zh-CN": "曲目详情页的讨论区与母带讨论区默认仅加载最新 20 条，并在列表顶部提供「加载更早的讨论」按钮按需回溯更早内容，避免一次性拉取全部历史影响响应速度。母带沟通侧边栏（聊天室）保持原有的完整加载行为不变。",
              "en": "The discussion panel on the track detail page and the mastering discussion panel now load only the 20 most recent entries by default, with a \"Load earlier discussions\" button at the top of the list for retrieving older content on demand. This avoids fetching the full history upfront, which could affect responsiveness. The mastering communication sidebar (chat) retains its existing full-load behavior."
            }
          },
          {
            "title": {
              "zh-CN": "新增评论中引用问题的能力",
              "en": "Added the ability to reference issues within comments"
            },
            "description": {
              "zh-CN": "在评论中输入 @issue:1 即可引用当前曲目的 1 号问题。问题编号以曲目为单位独立计数，不跨曲目共享，每首曲目均从 1 号起编。",
              "en": "Entering @issue:1 in a comment references issue #1 of the current track. Issue numbering is scoped to each track rather than shared globally, with every track starting from #1."
            }
          },
          {
            "title": {
              "zh-CN": "新增带索引的附件时间戳语法",
              "en": "Added indexed attachment timestamp syntax"
            },
            "description": {
              "zh-CN": "当评论包含多个音频附件时，可使用 a1:01:23、a2:00:45 的格式指向特定附件的特定时间点，便于在评审与沟通中精确定位音频位置。",
              "en": "When a comment contains multiple audio attachments, references in the form a1:01:23 or a2:00:45 may be used to point at a specific moment within a specific attachment, enabling precise audio referencing during review and discussion."
            }
          },
          {
            "title": {
              "zh-CN": "优化问题抽屉交互",
              "en": "Improved issue drawer interaction"
            },
            "description": {
              "zh-CN": "问题抽屉内新增内嵌波形预览与播放控件，无需离开当前页面即可试听并定位时间点。",
              "en": "An inline waveform preview and playback controls have been added to the issue drawer, allowing audition and seeking without leaving the current page."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "后台管理",
          "en": "Admin Console"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新增后台治理与审计能力",
              "en": "Added governance and audit capabilities to the admin console"
            },
            "description": {
              "zh-CN": "管理员可在后台控制台中集中处理账号状态、社团与专辑治理等事务，并可回溯关键操作的审计记录。",
              "en": "Administrators can now centrally manage account status as well as circle and album governance within the admin console, and review an audit trail of key actions."
            }
          },
          {
            "title": {
              "zh-CN": "后台控制台完成全量国际化",
              "en": "Admin console has been fully internationalized"
            },
            "description": {
              "zh-CN": "后台控制台支持中英双语切换，与系统其他界面保持一致。",
              "en": "The admin console now supports switching between Chinese and English, consistent with the rest of the system."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "工作流与仪表盘",
          "en": "Workflow & Dashboard"
        },
        "items": [
          {
            "title": {
              "zh-CN": "优化专辑创建流程",
              "en": "Improved the album creation flow"
            },
            "description": {
              "zh-CN": "新建专辑所需的操作步骤与页面跳转得到进一步精简。",
              "en": "The number of steps and page transitions required to create a new album has been further reduced."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作流模板一致性",
              "en": "Improved consistency across workflow templates"
            },
            "description": {
              "zh-CN": "对多种同行评审 → 主催审批 → 母带 → 终审的工作流变体进行行为对齐，降低在不同模板间切换时的体验差异。",
              "en": "Behavior across multiple peer-review → producer-gate → mastering → final-review workflow variants has been aligned, reducing experience discrepancies when switching between templates."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作流步骤完成后的跳转逻辑",
              "en": "Improved navigation after completing a workflow step"
            },
            "description": {
              "zh-CN": "完成某一步骤后将自动返回曲目详情页，不再停留在已结束的步骤工作台。",
              "en": "Upon completing a step, the view now automatically returns to the track detail page rather than remaining on the finished step workspace."
            }
          },
          {
            "title": {
              "zh-CN": "优化工作台抽屉体验",
              "en": "Improved the workspace drawer experience"
            },
            "description": {
              "zh-CN": "问题的创建、回复与处理可直接在抽屉内完成，无需跳转至独立的问题详情页。",
              "en": "Issue creation, reply, and resolution can now be performed directly within the drawer, without navigating to the standalone issue detail page."
            }
          },
          {
            "title": {
              "zh-CN": "优化仪表盘筛选",
              "en": "Improved dashboard filtering"
            },
            "description": {
              "zh-CN": "被拒曲目不再混入主列表，支持独立加载与筛选。",
              "en": "Rejected tracks are no longer mixed into the main list and can be loaded and filtered independently."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "母带阶段",
          "en": "Mastering Stage"
        },
        "items": [
          {
            "title": {
              "zh-CN": "修复母带侧边栏显示问题，精简母带历史条目",
              "en": "Fixed mastering sidebar visibility and simplified history entries"
            },
            "description": {
              "zh-CN": "修复在特定条件下曲目详情页无法显示母带侧边栏的问题，同时对母带历史条目的视觉呈现进行了精简。",
              "en": "Fixed an issue where the mastering sidebar could fail to display on the track detail page, and streamlined the visual presentation of mastering history entries."
            }
          },
          {
            "title": {
              "zh-CN": "修复母带相关页面的面包屑与入口",
              "en": "Fixed breadcrumbs and entry point on mastering pages"
            },
            "description": {
              "zh-CN": "修复母带相关页面顶部面包屑的标签显示，调整母带沟通入口的视觉权重。",
              "en": "Corrected breadcrumb labels on mastering-related pages and adjusted the visual weight of the mastering communication entry point."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "专辑导出",
          "en": "Album Export"
        },
        "items": [
          {
            "title": {
              "zh-CN": "导出音频自动写入专辑目录号",
              "en": "Exported audio automatically embeds the album catalog number"
            },
            "description": {
              "zh-CN": "专辑目录号（Catalog Number）将自动写入导出音频文件的元数据，便于交付压盘与发行环节使用，同时利于本地归档。",
              "en": "The album catalog number is now automatically written into the metadata of exported audio files, supporting handoff to pressing and distribution as well as local archiving."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "下载与播放",
          "en": "Downloads & Playback"
        },
        "items": [
          {
            "title": {
              "zh-CN": "新增音频缓存机制",
              "en": "Added an audio caching mechanism"
            },
            "description": {
              "zh-CN": "对已播放或已下载的音频进行本地缓存，重复访问时不再重新发起网络请求，响应速度有所提升；缓存容量设有上限，不会无限制占用本地存储。",
              "en": "Previously played or downloaded audio is now cached locally, so repeated access no longer issues new network requests and responsiveness improves. The cache has an upper size limit and will not consume local storage without bound."
            }
          },
          {
            "title": {
              "zh-CN": "评论内音频附件改由受保护的下载路由提供",
              "en": "Audio attachments in comments now served via a protected download route"
            },
            "description": {
              "zh-CN": "评论内的音频附件仅登录且具备相应权限的用户可访问。",
              "en": "Audio attachments within comments are now accessible only to authenticated users with the appropriate permissions."
            }
          },
          {
            "title": {
              "zh-CN": "评论内音频附件的编号顺序稳定化",
              "en": "Stabilized audio attachment ordering within comments"
            },
            "description": {
              "zh-CN": "评论内附件的编号顺序已稳定化，a1:、a2: 等带索引的附件时间戳引用不再因上传顺序或页面刷新而发生偏移。",
              "en": "The numbering order of attachments within comments is now stable, and indexed attachment timestamp references such as a1: or a2: will no longer shift due to upload order or page refreshes."
            }
          }
        ]
      },
      {
        "heading": {
          "zh-CN": "安全性",
          "en": "Safety"
        },
        "items": [
          {
            "title": {
              "zh-CN": "关键不可逆操作新增二次确认",
              "en": "Added confirmation prompts for critical irreversible actions"
            },
            "description": {
              "zh-CN": "对关键不可逆操作（包括账号注销、母带交付确认、曲目拒绝等）增加了二次确认流程。",
              "en": "Confirmation dialogs have been added to critical irreversible actions, including account deletion, mastering delivery confirmation, and track rejection."
            }
          },
          {
            "title": {
              "zh-CN": "统一加载、空状态与错误提示",
              "en": "Unified loading, empty, and error states"
            },
            "description": {
              "zh-CN": "对各视图下的加载态、空状态与错误提示进行了统一；注册、上传等场景的输入校验也进一步收紧。",
              "en": "Loading, empty, and error states have been unified across views; input validation for scenarios such as registration and upload has also been tightened."
            }
          }
        ]
      }
    ]
  }
]
